"""add_curriculum_translation_tables

Revision ID: 24d0239bf94b
Revises: 509bb3400ef0
Create Date: 2026-09-07 09:42:48.840089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d0239bf94b'
down_revision: Union[str, Sequence[str], None] = '509bb3400ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_translations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('translated_title', sa.String(length=255), nullable=False),
    sa.Column('translated_script', sa.Text(), nullable=True),
    sa.Column('translated_objective', sa.Text(), nullable=True),
    sa.Column('translated_content', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'language_code', 'version', name='uq_lesson_translation_version')
    )
    op.create_index('idx_lesson_trans_lang', 'lesson_translations', ['lesson_id', 'language_code', 'is_active'], unique=False)
    op.create_index(op.f('ix_lesson_translations_is_active'), 'lesson_translations', ['is_active'], unique=False)
    op.create_index(op.f('ix_lesson_translations_language_code'), 'lesson_translations', ['language_code'], unique=False)
    op.create_index(op.f('ix_lesson_translations_lesson_id'), 'lesson_translations', ['lesson_id'], unique=False)
    op.create_table('activity_translations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('translated_title', sa.String(length=255), nullable=False),
    sa.Column('translated_instructions', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'language_code', 'version', name='uq_activity_translation_version')
    )
    op.create_index('idx_activity_trans_lang', 'activity_translations', ['activity_id', 'language_code', 'is_active'], unique=False)
    op.create_index(op.f('ix_activity_translations_activity_id'), 'activity_translations', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_translations_is_active'), 'activity_translations', ['is_active'], unique=False)
    op.create_index(op.f('ix_activity_translations_language_code'), 'activity_translations', ['language_code'], unique=False)
    op.create_table('assessment_translations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('translated_title', sa.String(length=255), nullable=False),
    sa.Column('translated_prompt', sa.Text(), nullable=False),
    sa.Column('translated_expected_response', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'language_code', 'version', name='uq_assessment_translation_version')
    )
    op.create_index('idx_assessment_trans_lang', 'assessment_translations', ['assessment_id', 'language_code', 'is_active'], unique=False)
    op.create_index(op.f('ix_assessment_translations_assessment_id'), 'assessment_translations', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_translations_is_active'), 'assessment_translations', ['is_active'], unique=False)
    op.create_index(op.f('ix_assessment_translations_language_code'), 'assessment_translations', ['language_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_translations_language_code'), table_name='assessment_translations')
    op.drop_index(op.f('ix_assessment_translations_is_active'), table_name='assessment_translations')
    op.drop_index(op.f('ix_assessment_translations_assessment_id'), table_name='assessment_translations')
    op.drop_index('idx_assessment_trans_lang', table_name='assessment_translations')
    op.drop_table('assessment_translations')
    op.drop_index(op.f('ix_activity_translations_language_code'), table_name='activity_translations')
    op.drop_index(op.f('ix_activity_translations_is_active'), table_name='activity_translations')
    op.drop_index(op.f('ix_activity_translations_activity_id'), table_name='activity_translations')
    op.drop_index('idx_activity_trans_lang', table_name='activity_translations')
    op.drop_table('activity_translations')
    op.drop_index(op.f('ix_lesson_translations_lesson_id'), table_name='lesson_translations')
    op.drop_index(op.f('ix_lesson_translations_language_code'), table_name='lesson_translations')
    op.drop_index(op.f('ix_lesson_translations_is_active'), table_name='lesson_translations')
    op.drop_index('idx_lesson_trans_lang', table_name='lesson_translations')
    op.drop_table('lesson_translations')
    # ### end Alembic commands ###
