"""add worksheet and worksheet_questions tables

Revision ID: 509bb3400ef0
Revises: 982c01d0b9b7
Create Date: 2026-09-03 01:57:51.227812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '509bb3400ef0'
down_revision: Union[str, Sequence[str], None] = '982c01d0b9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worksheets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language_code', sa.String(length=20), server_default='hi', nullable=False),
    sa.Column('source_language', sa.String(length=20), server_default='hi', nullable=False),
    sa.Column('worksheet_type', sa.String(length=50), nullable=False),
    sa.Column('difficulty_level', sa.String(length=50), server_default='beginner', nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('answer_key', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worksheets_is_active'), 'worksheets', ['is_active'], unique=False)
    op.create_index(op.f('ix_worksheets_language_code'), 'worksheets', ['language_code'], unique=False)
    op.create_index(op.f('ix_worksheets_lesson_id'), 'worksheets', ['lesson_id'], unique=False)
    op.create_table('worksheet_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worksheet_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('marks', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worksheet_id'], ['worksheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worksheet_questions_worksheet_id'), 'worksheet_questions', ['worksheet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worksheet_questions_worksheet_id'), table_name='worksheet_questions')
    op.drop_table('worksheet_questions')
    op.drop_index(op.f('ix_worksheets_lesson_id'), table_name='worksheets')
    op.drop_index(op.f('ix_worksheets_language_code'), table_name='worksheets')
    op.drop_index(op.f('ix_worksheets_is_active'), table_name='worksheets')
    op.drop_table('worksheets')
    # ### end Alembic commands ###
