"""add cluster to schools

Revision ID: 5a2b1bacf318
Revises: c0553a54abb4
Create Date: 2026-09-03 00:50:09.127042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a2b1bacf318'
down_revision: Union[str, Sequence[str], None] = 'c0553a54abb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('cluster', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'cluster')
    # ### end Alembic commands ###
