"""add curriculum tables

Revision ID: 982c01d0b9b7
Revises: 5a2b1bacf318
Create Date: 2026-09-03 01:11:01.549441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982c01d0b9b7'
down_revision: Union[str, Sequence[str], None] = '5a2b1bacf318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_classes_grade'), 'curriculum_classes', ['grade'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['curriculum_classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_class_id'), 'subjects', ['class_id'], unique=False)
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=False)
    op.create_table('learning_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nipun_domain', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_outcomes_code'), 'learning_outcomes', ['code'], unique=False)
    op.create_index(op.f('ix_learning_outcomes_subject_id'), 'learning_outcomes', ['subject_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learning_outcome_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('source_language', sa.String(length=20), server_default='hi', nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('teacher_script', sa.Text(), nullable=True),
    sa.Column('learning_objective', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learning_outcome_id'], ['learning_outcomes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_learning_outcome_id'), 'lessons', ['learning_outcome_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('materials', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_lesson_id'), 'activities', ['lesson_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('assessment_type', sa.String(length=50), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('expected_response', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_lesson_id'), 'assessments', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessments_lesson_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_activities_lesson_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_lessons_learning_outcome_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_learning_outcomes_subject_id'), table_name='learning_outcomes')
    op.drop_index(op.f('ix_learning_outcomes_code'), table_name='learning_outcomes')
    op.drop_table('learning_outcomes')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_class_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_curriculum_classes_grade'), table_name='curriculum_classes')
    op.drop_table('curriculum_classes')
    # ### end Alembic commands ###
