import { ClassGrade, SubjectCategory } from '../types/models';

export interface ClassSubjectFlashcard {
  id: string;
  grade: ClassGrade;
  subject: SubjectCategory;
  titleHindi: string;
  titleEnglish: string;
  nameHo: string;
  nameSanthali: string;
  nameMundari: string;
  scriptHo: string;
  scriptSanthali: string;
  scriptMundari: string;
  category: string;
  emoji: string;
  audioClipKey: string;
  quizOptions: {
    questionText: string;
    options: string[];
    correctIndex: number;
  };
}

export const FLASHCARD_MATRIX: Record<ClassGrade, Record<SubjectCategory, ClassSubjectFlashcard[]>> = {
  // =========================================================================
  // CLASS 1 (5 Cards per Subject)
  // =========================================================================
  '1': {
    evs: [
      {
        id: 'c1_evs_1', grade: '1', subject: 'evs',
        titleHindi: 'गाय (Cow - Uri / Gai)', titleEnglish: 'Cow',
        nameHo: 'Uri (उरी)', nameSanthali: 'Gai (ᱜᱟᱹᱭ)', nameMundari: 'Uri (उरी)',
        scriptHo: '𑢣𑣜𑣂', scriptSanthali: 'ᱜᱟᱹᱭ', scriptMundari: 'उरी',
        category: 'My Family & Animals (परिवार व पशु)', emoji: '🐄', audioClipKey: 'audio_cow',
        quizOptions: { questionText: "गाय को संथाली (Ol Chiki) में क्या कहते हैं?", options: ['ᱜᱟᱹᱭ (Gai)', 'ᱥᱮᱛᱟ (Seta)', 'ᱯᱩᱥᱤ (Pusi)', 'ᱫᱟᱨᱮ (Dare)'], correctIndex: 0 },
      },
      {
        id: 'c1_evs_2', grade: '1', subject: 'evs',
        titleHindi: 'पेड़ (Tree - Daru / Dare)', titleEnglish: 'Tree',
        nameHo: 'Daru (दारू)', nameSanthali: 'Dare (ᱫᱟᱨᱮ)', nameMundari: 'Daru (दारू)',
        scriptHo: '𑢵𑣁𑣜𑣉', scriptSanthali: 'ᱫᱟᱨᱮ', scriptMundari: 'दारू',
        category: 'Plants & Nature (पेड़-पौधे)', emoji: '🌳', audioClipKey: 'audio_tree',
        quizOptions: { questionText: "'पेड़' को हो (Ho) व मुंडारी भाषा में क्या कहते हैं?", options: ['Daru (दारू)', 'Da (पानी)', 'Baha (फूल)', 'Singi (सूरज)'], correctIndex: 0 },
      },
      {
        id: 'c1_evs_3', grade: '1', subject: 'evs',
        titleHindi: 'भात / भोजन (Food / Rice)', titleEnglish: 'Food',
        nameHo: 'Mandi (मांडी)', nameSanthali: 'Daka (ᱫᱟᱠᱟ)', nameMundari: 'Mandi (मांडी)',
        scriptHo: '𑢭𑣁𑣓𑣵𑣂', scriptSanthali: 'ᱫᱟᱠᱟ', scriptMundari: 'मांडी',
        category: 'Food (भोजन)', emoji: '🍚', audioClipKey: 'audio_food',
        quizOptions: { questionText: "संथाली में पके हुए भोजन/भात को क्या कहते हैं?", options: ['ᱫᱟᱠᱟ (Daka)', 'ᱫᱟᱜ (Dah)', 'ᱫᱟᱨᱮ (Dare)', 'ᱵᱟᱦᱟ (Baha)'], correctIndex: 0 },
      },
      {
        id: 'c1_evs_4', grade: '1', subject: 'evs',
        titleHindi: 'पानी (Water - Da / Dah)', titleEnglish: 'Water',
        nameHo: 'Da (दाः)', nameSanthali: 'Dah (ᱫᱟᱜ)', nameMundari: 'Da (दाः)',
        scriptHo: '𑢵𑣁', scriptSanthali: 'ᱫᱟᱜ', scriptMundari: 'दाः',
        category: 'Water (जल)', emoji: '💧', audioClipKey: 'audio_water',
        quizOptions: { questionText: "हो व मुंडारी में 'पानी' का सही उच्चारण क्या है?", options: ['दाः (Da)', 'दारू (Daru)', 'मांडी (Mandi)', 'सिंगी (Singi)'], correctIndex: 0 },
      },
      {
        id: 'c1_evs_5', grade: '1', subject: 'evs',
        titleHindi: 'सूरज (Sun - Singi / Sin)', titleEnglish: 'Sun',
        nameHo: 'Singi (सिंगी)', nameSanthali: 'Sin (ᱥᱤᱧ)', nameMundari: 'Singi (सिंगी)',
        scriptHo: '𑢝𑣂𑣊𑣂', scriptSanthali: 'ᱥᱤᱧ', scriptMundari: 'सिंगी',
        category: 'Nature (प्रकृति)', emoji: '☀️', audioClipKey: 'audio_sun',
        quizOptions: { questionText: "संथाली में 'सूरज' को क्या कहा जाता है?", options: ['ᱥᱤᱧ (Sin)', 'ᱪᱟᱸᱫᱚ (Chando)', 'ᱵᱩᱨᱩ (Buru)', 'ᱫᱟᱜ (Dah)'], correctIndex: 0 },
      },
    ],
    language_ho: [
      {
        id: 'c1_ho_1', grade: '1', subject: 'language_ho',
        titleHindi: 'वारंग क्षिति अक्षर 𑢹 (Ha)', titleEnglish: 'Letter Ha',
        nameHo: '𑢹 (Ha) - Johar', nameSanthali: 'Johar', nameMundari: 'Johar',
        scriptHo: '𑢹𑣉𑢯𑣁𑣜', scriptSanthali: 'ᱡᱚᱦᱟᱨ', scriptMundari: 'जोहार',
        category: 'Warang Chiti (वारंग क्षिति)', emoji: '𑢹', audioClipKey: 'audio_johar',
        quizOptions: { questionText: "वारंग क्षिति लिपि में 'जोहार' का पहला अक्षर कौन सा है?", options: ['𑢹 (Ha)', '𑢵 (Da)', '𑢷 (Ba)', '𑢭 (Ma)'], correctIndex: 0 },
      },
      {
        id: 'c1_ho_2', grade: '1', subject: 'language_ho',
        titleHindi: 'चिड़िया (Bird - Chene)', titleEnglish: 'Bird',
        nameHo: 'Chene (चेने)', nameSanthali: 'Chene', nameMundari: 'Chene',
        scriptHo: '𑢮𑣈𑣓𑣈', scriptSanthali: 'ᱪᱮᱬᱮ', scriptMundari: 'चेने',
        category: 'Ho Vocabulary', emoji: '🐦', audioClipKey: 'audio_bird',
        quizOptions: { questionText: "हो भाषा में 'चिड़िया' को क्या कहते हैं?", options: ['Chene (चेने)', 'Kula (कुला)', 'Haku (हाकु)', 'Seta (सेता)'], correctIndex: 0 },
      },
      {
        id: 'c1_ho_3', grade: '1', subject: 'language_ho',
        titleHindi: 'बाघ (Tiger - Kula)', titleEnglish: 'Tiger',
        nameHo: 'Kula (कुला)', nameSanthali: 'Tarup', nameMundari: 'Kula',
        scriptHo: '𑢢𑣉𑢚𑣁', scriptSanthali: 'ᱛᱟᱹᱨᱩᱵ', scriptMundari: 'कुला',
        category: 'Animals', emoji: '🐅', audioClipKey: 'audio_tiger',
        quizOptions: { questionText: "हो भाषा में बाघ को क्या कहते हैं?", options: ['Kula (कुला)', 'Hati (हाती)', 'Seta (सेता)', 'Uri (उरी)'], correctIndex: 0 },
      },
      {
        id: 'c1_ho_4', grade: '1', subject: 'language_ho',
        titleHindi: 'कुत्ता (Dog - Seta)', titleEnglish: 'Dog',
        nameHo: 'Seta (सेता)', nameSanthali: 'Seta', nameMundari: 'Seta',
        scriptHo: '𑢝𑣈𑣕𑣁', scriptSanthali: 'ᱥᱮᱛᱟ', scriptMundari: 'सेता',
        category: 'Animals', emoji: '🐕', audioClipKey: 'audio_dog',
        quizOptions: { questionText: "हो भाषा में कुत्ते को क्या कहते हैं?", options: ['Seta (सेता)', 'Pusi (पुसी)', 'Kula (कुला)', 'Hati (हाती)'], correctIndex: 0 },
      },
      {
        id: 'c1_ho_5', grade: '1', subject: 'language_ho',
        titleHindi: 'मछली (Fish - Haku)', titleEnglish: 'Fish',
        nameHo: 'Haku (हाकु)', nameSanthali: 'Haku', nameMundari: 'Hai',
        scriptHo: '𑢹𑣁𑢢𑣉', scriptSanthali: 'ᱦᱟᱹᱠᱩ', scriptMundari: 'हाई',
        category: 'Water Animals', emoji: '🐟', audioClipKey: 'audio_fish',
        quizOptions: { questionText: "हो भाषा में मछली को क्या कहते हैं?", options: ['Haku (हाकु)', 'Uri (उरी)', 'Buru (बुरु)', 'Gada (गाडा)'], correctIndex: 0 },
      },
    ],
    language_santhali: [
      {
        id: 'c1_san_1', grade: '1', subject: 'language_santhali',
        titleHindi: 'ओल चिकी वर्ण ᱚ (Laa)', titleEnglish: 'Letter Laa',
        nameHo: 'Ol Chiti', nameSanthali: 'ᱚ (Laa)', nameMundari: 'Akhor',
        scriptHo: '𑢣𑢚', scriptSanthali: 'ᱚ', scriptMundari: 'अक्षर',
        category: 'Ol Chiki', emoji: 'ᱚ', audioClipKey: 'audio_laa',
        quizOptions: { questionText: "ओल चिकी वर्णमाला का पहला अक्षर कौन सा है?", options: ['ᱚ (Laa)', 'ᱛ (At)', 'ᱜ (Ag)', 'ᱝ (Ang)'], correctIndex: 0 },
      },
      {
        id: 'c1_san_2', grade: '1', subject: 'language_santhali',
        titleHindi: 'बिल्ली (Cat - Pusi)', titleEnglish: 'Cat',
        nameHo: 'Bili', nameSanthali: 'Pusi (ᱯᱩᱥᱤ)', nameMundari: 'Bili',
        scriptHo: '𑢷𑣂𑢚𑣂', scriptSanthali: 'ᱯᱩᱥᱤ', scriptMundari: 'बिली',
        category: 'Animals', emoji: '🐱', audioClipKey: 'audio_cat',
        quizOptions: { questionText: "संथाली (Ol Chiki) में बिल्ली को क्या कहते हैं?", options: ['ᱯᱩᱥᱤ (Pusi)', 'ᱥᱮᱛᱟ (Seta)', 'ᱜᱟᱹᱭ (Gai)', 'ᱫᱟᱨᱮ (Dare)'], correctIndex: 0 },
      },
      {
        id: 'c1_san_3', grade: '1', subject: 'language_santhali',
        titleHindi: 'हाथी (Elephant - Hathi)', titleEnglish: 'Elephant',
        nameHo: 'Hati', nameSanthali: 'Hathi (ᱦᱟᱹᱛᱤ)', nameMundari: 'Hati',
        scriptHo: '𑢹𑣁𑣕𑣂', scriptSanthali: 'ᱦᱟᱹᱛᱤ', scriptMundari: 'हाती',
        category: 'Animals', emoji: '🐘', audioClipKey: 'audio_elephant',
        quizOptions: { questionText: "संथाली में हाथी को क्या लिखते हैं?", options: ['ᱦᱟᱹᱛᱤ (Hathi)', 'ᱥᱮᱛᱟ (Seta)', 'ᱛᱟᱹᱨᱩᱵ (Tarup)', 'ᱜᱟᱹᱭ (Gai)'], correctIndex: 0 },
      },
      {
        id: 'c1_san_4', grade: '1', subject: 'language_santhali',
        titleHindi: 'फूल (Flower - Baha)', titleEnglish: 'Flower',
        nameHo: 'Baha', nameSanthali: 'Baha (ᱵᱟᱦᱟ)', nameMundari: 'Baha',
        scriptHo: '𑢷𑣁𑢹𑣁', scriptSanthali: 'ᱵᱟᱦᱟ', scriptMundari: 'बाहा',
        category: 'Nature', emoji: '🌸', audioClipKey: 'audio_flower',
        quizOptions: { questionText: "संथाली में 'फूल' को क्या कहते हैं?", options: ['ᱵᱟᱦᱟ (Baha)', 'ᱫᱟᱨᱮ (Dare)', 'ᱫᱟᱜ (Dah)', 'ᱥᱤᱧ (Sin)'], correctIndex: 0 },
      },
      {
        id: 'c1_san_5', grade: '1', subject: 'language_santhali',
        titleHindi: 'अभिवादन (Johar)', titleEnglish: 'Greeting',
        nameHo: 'Johar', nameSanthali: 'Johar (ᱡᱚᱦᱟᱨ)', nameMundari: 'Johar',
        scriptHo: '𑢯𑣉𑢹𑣁𑣜', scriptSanthali: 'ᱡᱚᱦᱟᱨ', scriptMundari: 'जोहार',
        category: 'Greetings', emoji: '🙏', audioClipKey: 'audio_johar',
        quizOptions: { questionText: "संथाली भाषा में पारंपरिक अभिवादन क्या है?", options: ['ᱡᱚᱦᱟᱨ (Johar)', 'नमस्ते', 'Hello', 'Salam'], correctIndex: 0 },
      },
    ],
    language_mundari: [
      {
        id: 'c1_mun_1', grade: '1', subject: 'language_mundari',
        titleHindi: 'अभिवादन (Johar)', titleEnglish: 'Johar',
        nameHo: 'Johar', nameSanthali: 'Johar', nameMundari: 'Johar (जोहार)',
        scriptHo: '𑢯𑣉𑢹𑣁𑣜', scriptSanthali: 'ᱡᱚᱦᱟᱨ', scriptMundari: 'जोहार',
        category: 'Greetings', emoji: '🙏', audioClipKey: 'audio_johar',
        quizOptions: { questionText: "मुंडारी में 'नमस्ते' को क्या कहते हैं?", options: ['जोहार (Johar)', 'दाः (Da)', 'दारू (Daru)', 'मांडी (Mandi)'], correctIndex: 0 },
      },
      {
        id: 'c1_mun_2', grade: '1', subject: 'language_mundari',
        titleHindi: 'मछली (Fish - Hai)', titleEnglish: 'Fish',
        nameHo: 'Haku', nameSanthali: 'Haku', nameMundari: 'Hai (हाई)',
        scriptHo: '𑢹𑣁𑢢𑣉', scriptSanthali: 'ᱦᱟᱹᱠᱩ', scriptMundari: 'हाई',
        category: 'Animals', emoji: '🐟', audioClipKey: 'audio_fish',
        quizOptions: { questionText: "मुंडारी भाषा में मछली को क्या कहा जाता है?", options: ['हाई (Hai)', 'हाकु (Haku)', 'उरी (Uri)', 'सेता (Seta)'], correctIndex: 0 },
      },
      {
        id: 'c1_mun_3', grade: '1', subject: 'language_mundari',
        titleHindi: 'घर (House - Ora)', titleEnglish: 'House',
        nameHo: 'Owa', nameSanthali: 'Orak', nameMundari: 'Ora (ओड़ाः)',
        scriptHo: '𑢣𑢱𑣁', scriptSanthali: 'ᱚᱲᱟᱜ', scriptMundari: 'ओड़ाः',
        category: 'Home', emoji: '🏠', audioClipKey: 'audio_house',
        quizOptions: { questionText: "मुंडारी में 'घर' को क्या कहते हैं?", options: ['ओड़ाः (Ora)', 'इस्कुल (Iskul)', 'गाडा (Gada)', 'बुरु (Buru)'], correctIndex: 0 },
      },
      {
        id: 'c1_mun_4', grade: '1', subject: 'language_mundari',
        titleHindi: 'पहाड़ (Mountain - Buru)', titleEnglish: 'Mountain',
        nameHo: 'Buru', nameSanthali: 'Buru', nameMundari: 'Buru (बुरु)',
        scriptHo: '𑢷𑣉𑣜𑣉', scriptSanthali: 'ᱵᱩᱨᱩ', scriptMundari: 'बुरु',
        category: 'Nature', emoji: '🏔️', audioClipKey: 'audio_mountain',
        quizOptions: { questionText: "मुंडारी में 'पहाड़' को क्या कहा जाता है?", options: ['बुरु (Buru)', 'गाडा (Gada)', 'दारू (Daru)', 'हासा (Hasa)'], correctIndex: 0 },
      },
      {
        id: 'c1_mun_5', grade: '1', subject: 'language_mundari',
        titleHindi: 'नदी (River - Gada)', titleEnglish: 'River',
        nameHo: 'Gada', nameSanthali: 'Gada', nameMundari: 'Gada (गाडा)',
        scriptHo: '𑢩𑣁𑣵𑣁', scriptSanthali: 'ᱜᱟᱰᱟ', scriptMundari: 'गाडा',
        category: 'Nature', emoji: '🏞️', audioClipKey: 'audio_river',
        quizOptions: { questionText: "मुंडारी में 'नदी' को क्या कहते हैं?", options: ['गाडा (Gada)', 'बुरु (Buru)', 'बीर (Bir)', 'दाः (Da)'], correctIndex: 0 },
      },
    ],
    math: [
      {
        id: 'c1_math_1', grade: '1', subject: 'math',
        titleHindi: 'संख्या 1 (One)', titleEnglish: 'One',
        nameHo: 'Miyad', nameSanthali: 'Mit', nameMundari: 'Miyad',
        scriptHo: '𑢱𑣁𑣕', scriptSanthali: 'ᱢᱤᱫ', scriptMundari: 'मियद',
        category: 'Numbers 1–20', emoji: '1️⃣', audioClipKey: 'audio_num1',
        quizOptions: { questionText: "संख्या '1' को संथाली (Ol Chiki) में क्या कहते हैं?", options: ['ᱢᱤᱫ (Mit)', 'ᱵᱟᱨ (Bar)', 'ᱯᱮ (Pe)', 'ᱯᱳᱱ (Pone)'], correctIndex: 0 },
      },
      {
        id: 'c1_math_2', grade: '1', subject: 'math',
        titleHindi: 'संख्या 2 (Two)', titleEnglish: 'Two',
        nameHo: 'Bariya', nameSanthali: 'Bar', nameMundari: 'Bariya',
        scriptHo: '𑢷𑣁𑣜𑣂𑣅𑣁', scriptSanthali: 'ᱵᱟᱨ', scriptMundari: 'बरिया',
        category: 'Numbers 1–20', emoji: '2️⃣', audioClipKey: 'audio_num2',
        quizOptions: { questionText: "संख्या '2' को हो व मुंडारी में क्या कहते हैं?", options: ['Bariya (बरिया)', 'Miyad (मियद)', 'Apiya (अपिया)', 'Moya (मोया)'], correctIndex: 0 },
      },
      {
        id: 'c1_math_3', grade: '1', subject: 'math',
        titleHindi: 'संख्या 3 (Three)', titleEnglish: 'Three',
        nameHo: 'Apiya', nameSanthali: 'Pe', nameMundari: 'Apiya',
        scriptHo: '𑢡𑣉𑣂𑣅𑣁', scriptSanthali: 'ᱯᱮ', scriptMundari: 'अपिया',
        category: 'Numbers 1–20', emoji: '3️⃣', audioClipKey: 'audio_num3',
        quizOptions: { questionText: "संथाली में '3' को क्या कहा जाता है?", options: ['ᱯᱮ (Pe)', 'ᱵᱟᱨ (Bar)', 'ᱢᱤᱫ (Mit)', 'ᱢᱚᱬᱮ (Mone)'], correctIndex: 0 },
      },
      {
        id: 'c1_math_4', grade: '1', subject: 'math',
        titleHindi: 'गोल / वृत्त (Circle Shape)', titleEnglish: 'Circle Shape',
        nameHo: 'Gol', nameSanthali: 'Gol', nameMundari: 'Gol',
        scriptHo: '𑢩𑣉𑣚', scriptSanthali: 'ᱜᱳᱞ', scriptMundari: 'गोल',
        category: 'Shapes', emoji: '🔴', audioClipKey: 'audio_circle',
        quizOptions: { questionText: "रोटी या पहिए की आकृति कैसी होती है?", options: ['गोल / वृत्त (Circle)', 'चौकोर (Square)', 'त्रिकोण (Triangle)', 'शंकु'], correctIndex: 0 },
      },
      {
        id: 'c1_math_5', grade: '1', subject: 'math',
        titleHindi: 'सरल जोड़ (1 + 2 = ?)', titleEnglish: 'Addition',
        nameHo: 'Misa', nameSanthali: 'Mesawa', nameMundari: 'Juma',
        scriptHo: '𑢭𑣂𑣝𑣁', scriptSanthali: 'ᱢᱮᱥᱟ', scriptMundari: 'जुमा',
        category: 'Addition', emoji: '➕', audioClipKey: 'audio_add',
        quizOptions: { questionText: "१ + २ का मान क्या होगा?", options: ['३ (तीन / Apiya / Pe)', '२ (दो)', '४ (चार)', '५ (पाँच)'], correctIndex: 0 },
      },
    ],
    english: [
      {
        id: 'c1_eng_1', grade: '1', subject: 'english',
        titleHindi: 'Letter A - Apple', titleEnglish: 'Letter A - Apple',
        nameHo: 'Apple (सेब)', nameSanthali: 'Apple', nameMundari: 'Apple',
        scriptHo: 'Apple', scriptSanthali: 'Apple', scriptMundari: 'Apple',
        category: 'Alphabet', emoji: '🍎', audioClipKey: 'audio_a',
        quizOptions: { questionText: "Which letter does 'Apple' start with?", options: ['Letter A', 'Letter B', 'Letter C', 'Letter D'], correctIndex: 0 },
      },
      {
        id: 'c1_eng_2', grade: '1', subject: 'english',
        titleHindi: 'Letter B - Ball', titleEnglish: 'Letter B - Ball',
        nameHo: 'Ball', nameSanthali: 'Ball', nameMundari: 'Ball',
        scriptHo: 'Ball', scriptSanthali: 'Ball', scriptMundari: 'Ball',
        category: 'Phonics', emoji: '⚽', audioClipKey: 'audio_b',
        quizOptions: { questionText: "What is the phonics sound of letter 'B'?", options: ['/b/ as in Ball', '/k/ as in Cat', '/s/ as in Sun', '/d/ as in Dog'], correctIndex: 0 },
      },
      {
        id: 'c1_eng_3', grade: '1', subject: 'english',
        titleHindi: 'Colour: Green (हरा)', titleEnglish: 'Colour: Green',
        nameHo: 'Haria', nameSanthali: 'Hariyad', nameMundari: 'Haria',
        scriptHo: 'Green', scriptSanthali: 'ᱦᱟᱹᱨᱤᱭᱟᱹᱲ', scriptMundari: 'हरा',
        category: 'Colours', emoji: '🟢', audioClipKey: 'audio_green',
        quizOptions: { questionText: "What is the colour of plant leaves?", options: ['Green (हरा)', 'Red (लाल)', 'Blue (नीला)', 'Yellow (पीला)'], correctIndex: 0 },
      },
      {
        id: 'c1_eng_4', grade: '1', subject: 'english',
        titleHindi: 'Number Five (5)', titleEnglish: 'Number Five',
        nameHo: 'Moya', nameSanthali: 'Mone', nameMundari: 'Moya',
        scriptHo: 'Five', scriptSanthali: 'ᱢᱚᱬᱮ', scriptMundari: 'पाँच',
        category: 'Numbers', emoji: '5️⃣', audioClipKey: 'audio_five',
        quizOptions: { questionText: "How many fingers do we have in one hand?", options: ['Five (5)', 'Four (4)', 'Six (6)', 'Three (3)'], correctIndex: 0 },
      },
      {
        id: 'c1_eng_5', grade: '1', subject: 'english',
        titleHindi: 'Word: School (विद्यालय)', titleEnglish: 'School',
        nameHo: 'Iskul', nameSanthali: 'Asra', nameMundari: 'Iskul',
        scriptHo: 'School', scriptSanthali: 'ᱟᱥᱲᱟ', scriptMundari: 'स्कूल',
        category: 'Simple Words', emoji: '🏫', audioClipKey: 'audio_school',
        quizOptions: { questionText: "Where do children go to learn and study?", options: ['School', 'Market', 'Cinema', 'Jungle'], correctIndex: 0 },
      },
    ],
    science: [],
    hindi: [],
  },

  // =========================================================================
  // CLASS 2 (5 Cards per Subject)
  // =========================================================================
  '2': {
    evs: [
      {
        id: 'c2_evs_1', grade: '2', subject: 'evs',
        titleHindi: 'हाथ (Hand - Ti)', titleEnglish: 'Hand',
        nameHo: 'Ti (ती)', nameSanthali: 'Ti (ᱛᱤ)', nameMundari: 'Ti (ती)',
        scriptHo: '𑢕𑣂', scriptSanthali: 'ᱛᱤ', scriptMundari: 'ती',
        category: 'Body Parts (शरीर के अंग)', emoji: '✋', audioClipKey: 'audio_hand',
        quizOptions: { questionText: "हो, संथाली व मुंडारी में 'हाथ' को क्या कहते हैं?", options: ['Ti (ती / ᱛᱤ)', 'Med (आँख)', 'Lutur (कान)', 'Macha (मुँह)'], correctIndex: 0 },
      },
      {
        id: 'c2_evs_2', grade: '2', subject: 'evs',
        titleHindi: 'आँख (Eye - Med / Met)', titleEnglish: 'Eye',
        nameHo: 'Med (मेद)', nameSanthali: 'Met (ᱢᱮᱫ)', nameMundari: 'Med (मेद)',
        scriptHo: '𑢭𑣈𑣵', scriptSanthali: 'ᱢᱮᱫ', scriptMundari: 'मेद',
        category: 'Sense Organs', emoji: '👀', audioClipKey: 'audio_eye',
        quizOptions: { questionText: "संथाली में 'आँख' को क्या कहा जाता है?", options: ['ᱢᱮᱫ (Met)', 'ᱞᱩᱛᱩᱨ (Lutur)', 'ᱛᱤ (Ti)', 'ᱡᱟᱝᱜᱟ (Janga)'], correctIndex: 0 },
      },
      {
        id: 'c2_evs_3', grade: '2', subject: 'evs',
        titleHindi: 'कान (Ear - Lutur)', titleEnglish: 'Ear',
        nameHo: 'Lutur (लुतुर)', nameSanthali: 'Lutur (ᱞᱩᱛᱩᱨ)', nameMundari: 'Lutur (लुतुर)',
        scriptHo: '𑢚𑣉𑣕𑣉𑣜', scriptSanthali: 'ᱞᱩᱛᱩᱨ', scriptMundari: 'लुतुर',
        category: 'Sense Organs', emoji: '👂', audioClipKey: 'audio_ear',
        quizOptions: { questionText: "ध्वनि सुनने के लिए हम किस अंग का उपयोग करते हैं?", options: ['Lutur / कान', 'Ti / हाथ', 'Med / आँख', 'Kata / पैर'], correctIndex: 0 },
      },
      {
        id: 'c2_evs_4', grade: '2', subject: 'evs',
        titleHindi: 'वर्षा ऋतु (Monsoon / Rain)', titleEnglish: 'Monsoon',
        nameHo: 'Gama da', nameSanthali: 'Dah Jari (ᱫᱟᱜ ᱡᱟᱹᱲᱤ)', nameMundari: 'Gama',
        scriptHo: '𑢩𑣁𑣭𑣁 𑢵𑣁', scriptSanthali: 'ᱫᱟᱜ ᱡᱟᱹᱲᱤ', scriptMundari: 'गामा',
        category: 'Seasons (ऋतुएँ)', emoji: '🌧️', audioClipKey: 'audio_rain',
        quizOptions: { questionText: "हो भाषा में बारिश/वर्षा ऋतु को क्या कहते हैं?", options: ['Gama da (गामा दाः)', 'Jeten (धूप)', 'Raban (सर्दी)', 'Singi (सूरज)'], correctIndex: 0 },
      },
      {
        id: 'c2_evs_5', grade: '2', subject: 'evs',
        titleHindi: 'मेरा विद्यालय (My School)', titleEnglish: 'My School',
        nameHo: 'Iskul', nameSanthali: 'Asra (ᱟᱥᱲᱟ)', nameMundari: 'Iskul',
        scriptHo: '𑢡𑣂𑣝𑢢𑣉𑢚', scriptSanthali: 'ᱟᱥᱲᱟ', scriptMundari: 'स्कूल',
        category: 'School (विद्यालय)', emoji: '🏫', audioClipKey: 'audio_school',
        quizOptions: { questionText: "संथाली (Ol Chiki) में स्कूल को क्या लिखते हैं?", options: ['ᱟᱥᱲᱟ (Asra)', 'ᱯᱩᱛᱷᱤ (Puthi)', 'ᱠᱚᱞᱚᱢ (Kalam)', 'ᱢᱟᱪᱮᱛ (Machet)'], correctIndex: 0 },
      },
    ],
    language_ho: [
      {
        id: 'c2_ho_1', grade: '2', subject: 'language_ho',
        titleHindi: 'किताब (Book - Pothi)', titleEnglish: 'Book',
        nameHo: 'Pothi (पोथी)', nameSanthali: 'Puthi', nameMundari: 'Pothi',
        scriptHo: '𑢰𑣉𑣕𑣂', scriptSanthali: 'ᱯᱩᱛᱷᱤ', scriptMundari: 'पोथी',
        category: 'Words', emoji: '📖', audioClipKey: 'audio_book',
        quizOptions: { questionText: "हो व मुंडारी में 'पुस्तक/किताब' को क्या कहते हैं?", options: ['Pothi (पोथी)', 'Kalam (कलम)', 'Iskul (स्कूल)', 'Kakhsa'], correctIndex: 0 },
      },
      {
        id: 'c2_ho_2', grade: '2', subject: 'language_ho',
        titleHindi: 'कलम (Pen - Kalam)', titleEnglish: 'Pen',
        nameHo: 'Kalam (कलम)', nameSanthali: 'Kalam', nameMundari: 'Kalam',
        scriptHo: '𑢢𑣁𑢚𑣁𑣭', scriptSanthali: 'ᱠᱚᱞᱚᱢ', scriptMundari: 'कलम',
        category: 'Stationery', emoji: '✏️', audioClipKey: 'audio_pen',
        quizOptions: { questionText: "लिखने वाले साधन (कलम) को वारंग क्षिति में क्या लिखते हैं?", options: ['𑢢𑣁𑢚𑣁𑣭 (Kalam)', '𑢰𑣉𑣕𑣂 (Pothi)', '𑢣𑢚 (Ol)', '𑢵𑣁𑣜𑣉 (Daru)'], correctIndex: 0 },
      },
      {
        id: 'c2_ho_3', grade: '2', subject: 'language_ho',
        titleHindi: 'पढ़ना (To Read - Padao)', titleEnglish: 'To Read',
        nameHo: 'Padao (पड़ाव)', nameSanthali: 'Parhao', nameMundari: 'Padao',
        scriptHo: '𑢰𑣁𑣵𑣁𑣉', scriptSanthali: 'ᱯᱟᱲᱦᱟᱣ', scriptMundari: 'पड़ाव',
        category: 'Action Verbs', emoji: '🧑‍🏫', audioClipKey: 'audio_read',
        quizOptions: { questionText: "हो भाषा में 'किताब पढ़ना' को क्या कहेंगे?", options: ['Pothi padao', 'Pothi ol', 'Pothi inung', 'Pothi durang'], correctIndex: 0 },
      },
      {
        id: 'c2_ho_4', grade: '2', subject: 'language_ho',
        titleHindi: 'लिखना (To Write - Ol)', titleEnglish: 'To Write',
        nameHo: 'Ol (ओल)', nameSanthali: 'Ol', nameMundari: 'Ol',
        scriptHo: '𑢣𑢚', scriptSanthali: 'ᱚᱞ', scriptMundari: 'ओल',
        category: 'Action Verbs', emoji: '✍️', audioClipKey: 'audio_write',
        quizOptions: { questionText: "'लिखना' को हो, संथाली व मुंडारी तीनों में क्या कहते हैं?", options: ['Ol (ओल)', 'Padao (पड़ाव)', 'Kaji (काजी)', 'Durang'], correctIndex: 0 },
      },
      {
        id: 'c2_ho_5', grade: '2', subject: 'language_ho',
        titleHindi: 'खेलना (To Play - Inung)', titleEnglish: 'To Play',
        nameHo: 'Inung (इनुंग)', nameSanthali: 'Enech', nameMundari: 'Enen',
        scriptHo: '𑢡𑣂𑣓𑣉𑣊', scriptSanthali: 'ᱮᱱᱮᱡ', scriptMundari: 'एनेन',
        category: 'Activities', emoji: '⚽', audioClipKey: 'audio_play',
        quizOptions: { questionText: "हो भाषा में 'खेलना' को क्या कहते हैं?", options: ['Inung (इनुंग)', 'Durang (गाना)', 'Susun (नाचना)', 'Sen (चलना)'], correctIndex: 0 },
      },
    ],
    language_santhali: [
      {
        id: 'c2_san_1', grade: '2', subject: 'language_santhali',
        titleHindi: 'किताब (Puthi - ᱯᱩᱛᱷᱤ)', titleEnglish: 'Book',
        nameHo: 'Pothi', nameSanthali: 'Puthi (ᱯᱩᱛᱷᱤ)', nameMundari: 'Pothi',
        scriptHo: '𑢰𑣉𑣕𑣂', scriptSanthali: 'ᱯᱩᱛᱷᱤ', scriptMundari: 'पोथी',
        category: 'Words', emoji: '📖', audioClipKey: 'audio_book',
        quizOptions: { questionText: "संथाली (Ol Chiki) में 'किताब' कैसे लिखते हैं?", options: ['ᱯᱩᱛᱷᱤ (Puthi)', 'ᱠᱚᱞᱚᱢ (Kalam)', 'ᱟᱥᱲᱟ (Asra)', 'ᱚᱞ (Ol)'], correctIndex: 0 },
      },
      {
        id: 'c2_san_2', grade: '2', subject: 'language_santhali',
        titleHindi: 'गाना (Song - Sereng)', titleEnglish: 'Song',
        nameHo: 'Durang', nameSanthali: 'Sereng (ᱥᱮᱨᱮᱧ)', nameMundari: 'Durang',
        scriptHo: '𑢵𑣉𑣜𑣁𑣊', scriptSanthali: 'ᱥᱮᱨᱮᱧ', scriptMundari: 'दुरंग',
        category: 'Music', emoji: '🎵', audioClipKey: 'audio_song',
        quizOptions: { questionText: "संथाली में गीत/गाने को क्या कहते हैं?", options: ['ᱥᱮᱨᱮᱧ (Sereng)', 'ᱮᱱᱮᱡ (Enech)', 'ᱚᱞ (Ol)', 'ᱨᱚᱲ (Ror)'], correctIndex: 0 },
      },
      {
        id: 'c2_san_3', grade: '2', subject: 'language_santhali',
        titleHindi: 'बोलना (To Speak - Ror)', titleEnglish: 'To Speak',
        nameHo: 'Kaji', nameSanthali: 'Ror (ᱨᱚᱲ)', nameMundari: 'Kaji',
        scriptHo: '𑢢𑣁𑢯𑣂', scriptSanthali: 'ᱨᱚᱲ', scriptMundari: 'काजी',
        category: 'Language Skills', emoji: '🗣️', audioClipKey: 'audio_speak',
        quizOptions: { questionText: "संथाली में 'बोलना' को क्या कहते हैं?", options: ['ᱨᱚᱲ (Ror)', 'ᱚᱞ (Ol)', 'ᱯᱟᱲᱦᱟᱣ (Parhao)', 'ᱮᱱᱮᱡ (Enech)'], correctIndex: 0 },
      },
      {
        id: 'c2_san_4', grade: '2', subject: 'language_santhali',
        titleHindi: 'शिक्षक (Teacher - Machet)', titleEnglish: 'Teacher',
        nameHo: 'Masaab', nameSanthali: 'Machet (ᱢᱟᱪᱮᱛ)', nameMundari: 'Master',
        scriptHo: '𑢭𑣁𑣝𑣁𑢷', scriptSanthali: 'ᱢᱟᱪᱮᱛ', scriptMundari: 'गुरुजी',
        category: 'School Members', emoji: '👨‍🏫', audioClipKey: 'audio_teacher',
        quizOptions: { questionText: "संथाली में शिक्षक को क्या कहते हैं?", options: ['ᱢᱟᱪᱮᱛ (Machet)', 'ᱜᱟᱛᱮ (Gati)', 'ᱦᱚᱲ (Hor)', 'ᱟᱛᱳ (Ato)'], correctIndex: 0 },
      },
      {
        id: 'c2_san_5', grade: '2', subject: 'language_santhali',
        titleHindi: 'मित्र / दोस्त (Friend - Gati)', titleEnglish: 'Friend',
        nameHo: 'Gati', nameSanthali: 'Gati (ᱜᱟᱛᱮ)', nameMundari: 'Joti',
        scriptHo: '𑢩𑣁𑣕𑣂', scriptSanthali: 'ᱜᱟᱛᱮ', scriptMundari: 'जोती',
        category: 'Relationships', emoji: '🤝', audioClipKey: 'audio_friend',
        quizOptions: { questionText: "संथाली व हो में 'दोस्त/मित्र' को क्या कहते हैं?", options: ['ᱜᱟᱛᱮ (Gati)', 'ᱢᱟᱪᱮᱛ (Machet)', 'ᱟᱥᱲᱟ (Asra)', 'ᱚᱲᱟᱜ (Orak)'], correctIndex: 0 },
      },
    ],
    language_mundari: [
      {
        id: 'c2_mun_1', grade: '2', subject: 'language_mundari',
        titleHindi: 'किताब (Pothi)', titleEnglish: 'Book',
        nameHo: 'Pothi', nameSanthali: 'Puthi', nameMundari: 'Pothi (पोथी)',
        scriptHo: '𑢰𑣉𑣕𑣂', scriptSanthali: 'ᱯᱩᱛᱷᱤ', scriptMundari: 'पोथी',
        category: 'School Words', emoji: '📖', audioClipKey: 'audio_book',
        quizOptions: { questionText: "मुंडारी में 'किताब' को क्या कहते हैं?", options: ['पोथी (Pothi)', 'कलम (Kalam)', 'इस्कुल (Iskul)', 'गाडा (Gada)'], correctIndex: 0 },
      },
      {
        id: 'c2_mun_2', grade: '2', subject: 'language_mundari',
        titleHindi: 'गाना (Song - Durang)', titleEnglish: 'Song',
        nameHo: 'Durang', nameSanthali: 'Sereng', nameMundari: 'Durang (दुरंग)',
        scriptHo: '𑢵𑣉𑣜𑣁𑣊', scriptSanthali: 'ᱥᱮᱨᱮᱧ', scriptMundari: 'दुरंग',
        category: 'Music', emoji: '🎵', audioClipKey: 'audio_song',
        quizOptions: { questionText: "मुंडारी व हो में 'गीत/गाना' को क्या कहते हैं?", options: ['दुरंग (Durang)', 'सुसुन (Susun)', 'एनेन (Enen)', 'काजी (Kaji)'], correctIndex: 0 },
      },
      {
        id: 'c2_mun_3', grade: '2', subject: 'language_mundari',
        titleHindi: 'नाचना (Dance - Susun)', titleEnglish: 'Dance',
        nameHo: 'Susun', nameSanthali: 'Enech', nameMundari: 'Susun (सुसुन)',
        scriptHo: '𑢝𑣉𑣝𑣉𑣓', scriptSanthali: 'ᱮᱱᱮᱡ', scriptMundari: 'सुसुन',
        category: 'Culture', emoji: '💃', audioClipKey: 'audio_dance',
        quizOptions: { questionText: "मांदर की थाप पर आदिवासी नृत्य को क्या कहते हैं?", options: ['सुसुन (Susun)', 'दुरंग (Durang)', 'काजी (Kaji)', 'पड़ाव (Padao)'], correctIndex: 0 },
      },
      {
        id: 'c2_mun_4', grade: '2', subject: 'language_mundari',
        titleHindi: 'मित्र (Friend - Joti)', titleEnglish: 'Friend',
        nameHo: 'Gati', nameSanthali: 'Gati', nameMundari: 'Joti (जोती)',
        scriptHo: '𑢩𑣁𑣕𑣂', scriptSanthali: 'ᱜᱟᱛᱮ', scriptMundari: 'जोती',
        category: 'Friends', emoji: '🤝', audioClipKey: 'audio_friend',
        quizOptions: { questionText: "मुंडारी में सहपाठी मित्र को क्या कहते हैं?", options: ['जोती (Joti)', 'माचेत', 'इस्कुल', 'ओड़ाः'], correctIndex: 0 },
      },
      {
        id: 'c2_mun_5', grade: '2', subject: 'language_mundari',
        titleHindi: 'बोलना (To Speak - Kaji)', titleEnglish: 'To Speak',
        nameHo: 'Kaji', nameSanthali: 'Ror', nameMundari: 'Kaji (काजी)',
        scriptHo: '𑢢𑣁𑢯𑣂', scriptSanthali: 'ᱨᱚᱲ', scriptMundari: 'काजी',
        category: 'Language Skills', emoji: '🗣️', audioClipKey: 'audio_speak',
        quizOptions: { questionText: "मुंडारी में 'बातचीत करना / बोलना' को क्या कहते हैं?", options: ['काजी (Kaji)', 'ओल (Ol)', 'पड़ाव (Padao)', 'दुरंग (Durang)'], correctIndex: 0 },
      },
    ],
    math: [
      {
        id: 'c2_math_1', grade: '2', subject: 'math',
        titleHindi: 'संख्या 10 (Ten - Gel)', titleEnglish: 'Ten',
        nameHo: 'Gel', nameSanthali: 'Gele', nameMundari: 'Gel',
        scriptHo: '𑢩𑣈𑢚', scriptSanthali: 'ᱜᱮᱞ', scriptMundari: 'गेल',
        category: 'Numbers 1–100', emoji: '🔟', audioClipKey: 'audio_ten',
        quizOptions: { questionText: "संख्या '10' को संथाली (Ol Chiki) में क्या कहते हैं?", options: ['ᱜᱮᱞ (Gele)', 'ᱢᱤᱫ (Mit)', 'ᱵᱟᱨ (Bar)', 'ᱯᱮ (Pe)'], correctIndex: 0 },
      },
      {
        id: 'c2_math_2', grade: '2', subject: 'math',
        titleHindi: 'संख्या 20 (Twenty - Isi)', titleEnglish: 'Twenty',
        nameHo: 'Isi', nameSanthali: 'Mihsi', nameMundari: 'Mihsi',
        scriptHo: '𑢡𑣂𑣝𑣂', scriptSanthali: 'ᱤᱥᱤ', scriptMundari: 'इसी',
        category: 'Numbers 1–100', emoji: '2️⃣0️⃣', audioClipKey: 'audio_twenty',
        quizOptions: { questionText: "आदिवासी परंपरा में 'एक कोड़ी (२०)' को क्या कहते हैं?", options: ['Isi (इसी)', 'Gel (गेल)', 'Moya (मोया)', 'Apiya (अपिया)'], correctIndex: 0 },
      },
      {
        id: 'c2_math_3', grade: '2', subject: 'math',
        titleHindi: 'जोड़: 25 + 14 = 39', titleEnglish: 'Addition: 25 + 14',
        nameHo: 'Misa', nameSanthali: 'Mesawa', nameMundari: 'Juma',
        scriptHo: '25 + 14 = 39', scriptSanthali: '25 + 14 = 39', scriptMundari: '२५ + १४ = ३९',
        category: 'Addition', emoji: '➕', audioClipKey: 'audio_calc',
        quizOptions: { questionText: "२५ + १४ का सही जोड़ क्या होगा?", options: ['३९ (Thirty-Nine)', '३८ (Thirty-Eight)', '४० (Forty)', '२९ (Twenty-Nine)'], correctIndex: 0 },
      },
      {
        id: 'c2_math_4', grade: '2', subject: 'math',
        titleHindi: 'घटाव: 48 - 20 = 28', titleEnglish: 'Subtraction: 48 - 20',
        nameHo: 'Hating', nameSanthali: 'Ochoko', nameMundari: 'Ghatav',
        scriptHo: '48 - 20 = 28', scriptSanthali: '48 - 20 = 28', scriptMundari: '४८ - २० = २८',
        category: 'Subtraction', emoji: '➖', audioClipKey: 'audio_sub',
        quizOptions: { questionText: "४८ में से २० घटाने पर क्या बचेगा?", options: ['२८ (Twenty-Eight)', '१८ (Eighteen)', '३८ (Thirty-Eight)', '२२ (Twenty-Two)'], correctIndex: 0 },
      },
      {
        id: 'c2_math_5', grade: '2', subject: 'math',
        titleHindi: 'पैटर्न: 10, 20, 30, 40, ?', titleEnglish: 'Pattern',
        nameHo: 'Pattern', nameSanthali: 'Pattern', nameMundari: 'Pattern',
        scriptHo: '10, 20, 30, 40, 50', scriptSanthali: '10, 20, 30, 40, 50', scriptMundari: '१०, २०, ३०, ४०, ५०',
        category: 'Patterns', emoji: '🔢', audioClipKey: 'audio_pattern',
        quizOptions: { questionText: "पैटर्न में अगला अंक क्या होगा: १०, २०, ३०, ४०, ___?", options: ['५० (Fifty)', '४५ (Forty-Five)', '६० (Sixty)', '५५ (Fifty-Five)'], correctIndex: 0 },
      },
    ],
    english: [
      {
        id: 'c2_eng_1', grade: '2', subject: 'english',
        titleHindi: 'Plural: Book ➔ Books', titleEnglish: 'Plurals',
        nameHo: 'Pothiko', nameSanthali: 'Puthiko', nameMundari: 'Pothiko',
        scriptHo: 'Books', scriptSanthali: 'Books', scriptMundari: 'Books',
        category: 'Grammar', emoji: '📚', audioClipKey: 'audio_plurals',
        quizOptions: { questionText: "What is the plural form of 'Book'?", options: ['Books', 'Bookes', 'Bookies', 'Bookss'], correctIndex: 0 },
      },
      {
        id: 'c2_eng_2', grade: '2', subject: 'english',
        titleHindi: 'Action: Run (दौड़ना)', titleEnglish: 'Action: Run',
        nameHo: 'Nir', nameSanthali: 'Dạr (ᱫᱟᱹᱲ)', nameMundari: 'Nir',
        scriptHo: 'Run', scriptSanthali: 'ᱫᱟᱹᱲ', scriptMundari: 'दौड़ना',
        category: 'Action Verbs', emoji: '🏃‍♂️', audioClipKey: 'audio_run',
        quizOptions: { questionText: "What does the action word 'Run' mean?", options: ['दौड़ना / Running fast', 'सोना', 'खाना', 'बैठना'], correctIndex: 0 },
      },
      {
        id: 'c2_eng_3', grade: '2', subject: 'english',
        titleHindi: 'Sentence: "This is a cat."', titleEnglish: 'Simple Sentence',
        nameHo: 'Nena bili tana', nameSanthali: 'Nui do pusi kanae', nameMundari: 'Nia bili tana',
        scriptHo: 'This is a cat', scriptSanthali: 'This is a cat', scriptMundari: 'यह एक बिल्ली है',
        category: 'Sentences', emoji: '🐱', audioClipKey: 'audio_cat_sent',
        quizOptions: { questionText: "What is the Hindi meaning of 'This is a cat'?", options: ['यह एक बिल्ली है', 'वह एक कुत्ता है', 'यह एक गाय है', 'यह एक पक्षी है'], correctIndex: 0 },
      },
      {
        id: 'c2_eng_4', grade: '2', subject: 'english',
        titleHindi: 'Greeting: "Good Morning"', titleEnglish: 'Good Morning',
        nameHo: 'Bugi Seta', nameSanthali: 'Bogi Seta', nameMundari: 'Bugi Seta',
        scriptHo: 'Good Morning', scriptSanthali: 'Good Morning', scriptMundari: 'शुभ प्रभात',
        category: 'Greetings', emoji: '🌅', audioClipKey: 'audio_gm',
        quizOptions: { questionText: "When do we say 'Good Morning'?", options: ['In the morning (सुबह)', 'At night (रात में)', 'In evening', 'Never'], correctIndex: 0 },
      },
      {
        id: 'c2_eng_5', grade: '2', subject: 'english',
        titleHindi: 'Command: "Drink Water"', titleEnglish: 'Drink Water',
        nameHo: 'Da nuyenpe', nameSanthali: 'Dah nuyen me', nameMundari: 'Da nuyepe',
        scriptHo: 'Drink Water', scriptSanthali: 'Drink Water', scriptMundari: 'पानी पियो',
        category: 'Commands', emoji: '💧', audioClipKey: 'audio_drink',
        quizOptions: { questionText: "What does 'Drink Water' mean?", options: ['पानी पियो', 'खाना खाओ', 'किताब पढ़ो', 'घर जाओ'], correctIndex: 0 },
      },
    ],
    science: [],
    hindi: [],
  },

  // =========================================================================
  // CLASS 3 (5 Cards per Subject)
  // =========================================================================
  '3': {
    evs: [
      {
        id: 'c3_evs_1', grade: '3', subject: 'evs',
        titleHindi: 'नदी व जल स्रोत (River - Gada)', titleEnglish: 'River & Water Sources',
        nameHo: 'Gada (गाडा)', nameSanthali: 'Gada (ᱜᱟᱰᱟ)', nameMundari: 'Gada (गाडा)',
        scriptHo: '𑢩𑣁𑣵𑣁', scriptSanthali: 'ᱜᱟᱰᱟ', scriptMundari: 'गाडा',
        category: 'Water Resources (जल संसाधन)', emoji: '🏞️', audioClipKey: 'audio_river',
        quizOptions: { questionText: "झारखंड की प्रमुख नदियों (स्वर्णरेखा, दामोदर) को आदिवासी भाषा में क्या कहते हैं?", options: ['Gada (गाडा / ᱜᱟᱰᱟ)', 'Buru (पहाड़)', 'Bir (जंगल)', 'Hasa (मिट्टी)'], correctIndex: 0 },
      },
      {
        id: 'c3_evs_2', grade: '3', subject: 'evs',
        titleHindi: 'सखुआ / साल वृक्ष (Sarjom)', titleEnglish: 'Sal Tree (Sarjom)',
        nameHo: 'Sarjom (सरजोम)', nameSanthali: 'Sarjom (ᱥᱟᱨᱡᱚᱢ)', nameMundari: 'Sarjom (सरजोम)',
        scriptHo: '𑢝𑣁𑣜𑢯𑣉𑣭', scriptSanthali: 'ᱥᱟᱨᱡᱚᱢ', scriptMundari: 'सरजोम',
        category: 'Sacred Trees (पवित्र वृक्ष)', emoji: '🌳', audioClipKey: 'audio_sal',
        quizOptions: { questionText: "सरहुल पर्व पर किस वृक्ष के फूलों (बाहा) की पूजा की जाती है?", options: ['सखुआ / साल (Sarjom)', 'महुआ (Matkom)', 'आम (Uli)', 'जामुन (Kuda)'], correctIndex: 0 },
      },
      {
        id: 'c3_evs_3', grade: '3', subject: 'evs',
        titleHindi: 'मडुआ / रागी (Nutritious Grain)', titleEnglish: 'Finger Millet (Mandua)',
        nameHo: 'Kode (कोदे)', nameSanthali: 'Kode (ᱠᱚᱰᱮ)', nameMundari: 'Kode (कोदे)',
        scriptHo: '𑢢𑣉𑣵𑣈', scriptSanthali: 'ᱠᱚᱰᱮ', scriptMundari: 'कोदे',
        category: 'Traditional Nutrition (पोषण)', emoji: '🌾', audioClipKey: 'audio_grain',
        quizOptions: { questionText: "आदिवासी समाज में बच्चों के स्वास्थ्य के लिए कौन सा पारंपरिक अनाज कैल्शियम से भरपूर माना जाता है?", options: ['मडुआ / कोदे (Kode)', 'चावल (Daka)', 'गेहूँ', 'मक्का (Jondra)'], correctIndex: 0 },
      },
      {
        id: 'c3_evs_4', grade: '3', subject: 'evs',
        titleHindi: 'पहाड़ व पर्यावरण (Mountain - Buru)', titleEnglish: 'Mountain & Ecology',
        nameHo: 'Buru (बुरु)', nameSanthali: 'Buru (ᱵᱩᱨᱩ)', nameMundari: 'Buru (बुरु)',
        scriptHo: '𑢷𑣉𑣜𑣉', scriptSanthali: 'ᱵᱩᱨᱩ', scriptMundari: 'बुरु',
        category: 'Ecosystem', emoji: '🏔️', audioClipKey: 'audio_mountain',
        quizOptions: { questionText: "पहाड़ों और वनों के संरक्षण से हमें क्या लाभ मिलता है?", options: ['स्वच्छ जल व शुद्ध वायु', 'वर्षा का संतुलन', 'वनौषधि की प्राप्ति', 'उपर्युक्त सभी (All of above)'], correctIndex: 3 },
      },
      {
        id: 'c3_evs_5', grade: '3', subject: 'evs',
        titleHindi: 'जंगल / वन (Forest - Bir)', titleEnglish: 'Forest (Bir)',
        nameHo: 'Bir (बीर)', nameSanthali: 'Bir (ᱵᱤᱨ)', nameMundari: 'Bir (बीर)',
        scriptHo: '𑢷𑣂𑣜', scriptSanthali: 'ᱵᱤᱨ', scriptMundari: 'बीर',
        category: 'Biodiversity', emoji: '🌲', audioClipKey: 'audio_forest',
        quizOptions: { questionText: "हो, संथाली व मुंडारी तीनों भाषाओं में 'जंगल/वन' को क्या कहते हैं?", options: ['Bir (बीर / ᱵᱤᱨ)', 'Hasa (मिट्टी)', 'Da (पानी)', 'Orak (घर)'], correctIndex: 0 },
      },
    ],
    language_ho: [
      {
        id: 'c3_ho_1', grade: '3', subject: 'language_ho',
        titleHindi: 'फूल (Flower - Baha)', titleEnglish: 'Flower',
        nameHo: 'Baha (बाहा)', nameSanthali: 'Baha', nameMundari: 'Baha',
        scriptHo: '𑢷𑣁𑢹𑣁', scriptSanthali: 'ᱵᱟᱦᱟ', scriptMundari: 'बाहा',
        category: 'Nature', emoji: '🌸', audioClipKey: 'audio_baha',
        quizOptions: { questionText: "हो भाषा में 'बाहा' का क्या अर्थ है?", options: ['फूल (Flower)', 'पेड़ (Tree)', 'फल (Fruit)', 'पत्ता (Leaf)'], correctIndex: 0 },
      },
      {
        id: 'c3_ho_2', grade: '3', subject: 'language_ho',
        titleHindi: 'मागे परब (Mage Porob)', titleEnglish: 'Mage Festival',
        nameHo: 'Mage Porob', nameSanthali: 'Sohrai', nameMundari: 'Mage',
        scriptHo: '𑢭𑣁𑢩𑣈 𑢰𑣉𑣜𑣉𑢷', scriptSanthali: 'ᱥᱚᱦᱨᱟᱭ', scriptMundari: 'मागे परब',
        category: 'Festivals', emoji: '🥁', audioClipKey: 'audio_fest',
        quizOptions: { questionText: "हो समाज का प्रमुख शीतकालीन पर्व कौन सा है?", options: ['मागे परब (Mage Porob)', 'दीपावली', 'होली', 'दशहरा'], correctIndex: 0 },
      },
      {
        id: 'c3_ho_3', grade: '3', subject: 'language_ho',
        titleHindi: 'गाँव (Village - Hatu)', titleEnglish: 'Village',
        nameHo: 'Hatu (हातु)', nameSanthali: 'Ato', nameMundari: 'Hatu',
        scriptHo: '𑢹𑣁𑣕𑣉', scriptSanthali: 'ᱟᱛᱳ', scriptMundari: 'हातु',
        category: 'Community', emoji: '🏡', audioClipKey: 'audio_village',
        quizOptions: { questionText: "हो व मुंडारी में 'गाँव' को क्या कहते हैं?", options: ['Hatu (हातु)', 'Owa (घर)', 'Iskul', 'Bazaar'], correctIndex: 0 },
      },
      {
        id: 'c3_ho_4', grade: '3', subject: 'language_ho',
        titleHindi: 'सवेरा / सुबह (Morning - Seta)', titleEnglish: 'Morning',
        nameHo: 'Seta (सेताः)', nameSanthali: 'Seta (ᱥᱮᱛᱟᱜ)', nameMundari: 'Seta',
        scriptHo: '𑢝𑣈𑣕𑣁', scriptSanthali: 'ᱥᱮᱛᱟᱜ', scriptMundari: 'सेताः',
        category: 'Time', emoji: '🌅', audioClipKey: 'audio_morning',
        quizOptions: { questionText: "हो भाषा में 'सुबह/प्रभात' को क्या कहते हैं?", options: ['Seta (सेताः)', 'Tikli (दोपहर)', 'Aiyub (शाम)', 'Nida (रात)'], correctIndex: 0 },
      },
      {
        id: 'c3_ho_5', grade: '3', subject: 'language_ho',
        titleHindi: 'पानी पीना (Sentence - Da Nuyen)', titleEnglish: 'Drink Water',
        nameHo: 'Da nuyentana', nameSanthali: 'Dah nuyena', nameMundari: 'Da nuyetana',
        scriptHo: '𑢵𑣁 𑢓𑣉𑢱𑣈𑣓', scriptSanthali: 'ᱫᱟᱜ ᱧᱩᱭᱮᱫᱟ', scriptMundari: 'दाः नुयेतना',
        category: 'Sentences', emoji: '🥤', audioClipKey: 'audio_drink_ho',
        quizOptions: { questionText: "'मैं पानी पी रहा हूँ' को हो में क्या कहते हैं?", options: ['Aing da nuyentana', 'Aing mandi jomtana', 'Aing iskul senotana', 'Aing pothi ol'], correctIndex: 0 },
      },
    ],
    language_santhali: [
      {
        id: 'c3_san_1', grade: '3', subject: 'language_santhali',
        titleHindi: 'बाहा पर्व (Baha Parab)', titleEnglish: 'Baha Festival',
        nameHo: 'Baha Porob', nameSanthali: 'Baha Parab (ᱵᱟᱦᱟ ᱯᱚᱨᱚᱵᱽ)', nameMundari: 'Sarhul',
        scriptHo: '𑢷𑣁𑢹𑣁', scriptSanthali: 'ᱵᱟᱦᱟ ᱯᱚᱨᱚᱵᱽ', scriptMundari: 'बाहा पर्व',
        category: 'Festivals', emoji: '🌸', audioClipKey: 'audio_baha_san',
        quizOptions: { questionText: "संथाली समुदाय का वसंतकालीन पुष्प पर्व कौन सा है?", options: ['ᱵᱟᱦᱟ ᱯᱚᱨᱚᱵᱽ (Baha Parab)', 'ᱥᱚᱦᱨᱟᱭ (Sohrai)', 'ᱠᱟᱨᱟᱢ (Karam)', 'ᱫᱟᱥᱟᱸᱭ (Dasai)'], correctIndex: 0 },
      },
      {
        id: 'c3_san_2', grade: '3', subject: 'language_santhali',
        titleHindi: 'सोहराय पर्व (Sohrai Festival)', titleEnglish: 'Sohrai Festival',
        nameHo: 'Sohrai', nameSanthali: 'Sohrai (ᱥᱚᱦᱨᱟᱭ)', nameMundari: 'Sohrai',
        scriptHo: '𑢝𑣉𑢹𑣜𑣁𑢱', scriptSanthali: 'ᱥᱚᱦᱨᱟᱭ', scriptMundari: 'सोहराय',
        category: 'Festivals', emoji: '🎨', audioClipKey: 'audio_sohrai',
        quizOptions: { questionText: "पशुधन और भित्ति-चित्रकला से जुड़ा संथाली पर्व कौन सा है?", options: ['ᱥᱚᱦᱨᱟᱭ (Sohrai)', 'ᱵᱟᱦᱟ (Baha)', 'ᱢᱟᱜᱮ (Mage)', 'ᱮᱱᱮᱡ (Enech)'], correctIndex: 0 },
      },
      {
        id: 'c3_san_3', grade: '3', subject: 'language_santhali',
        titleHindi: 'गाँव (Village - Ato)', titleEnglish: 'Village',
        nameHo: 'Hatu', nameSanthali: 'Ato (ᱟᱛᱳ)', nameMundari: 'Hatu',
        scriptHo: '𑢹𑣁𑣕𑣉', scriptSanthali: 'ᱟᱛᱳ', scriptMundari: 'हातु',
        category: 'Community', emoji: '🏘️', audioClipKey: 'audio_ato',
        quizOptions: { questionText: "संथाली (Ol Chiki) में 'गाँव' को क्या कहते हैं?", options: ['ᱟᱛᱳ (Ato)', 'ᱚᱲᱟᱜ (Orak)', 'ᱟᱥᱲᱟ (Asra)', 'ᱵᱤᱨ (Bir)'], correctIndex: 0 },
      },
      {
        id: 'c3_san_4', grade: '3', subject: 'language_santhali',
        titleHindi: 'रात (Night - Ninda)', titleEnglish: 'Night',
        nameHo: 'Nida', nameSanthali: 'Ninda (ᱧᱤᱫᱟᱹ)', nameMundari: 'Nida',
        scriptHo: '𑢓𑣂𑣵𑣁', scriptSanthali: 'ᱧᱤᱫᱟᱹ', scriptMundari: 'निदाः',
        category: 'Time', emoji: '🌙', audioClipKey: 'audio_ninda',
        quizOptions: { questionText: "संथाली में 'रात/रात्रि' को क्या कहा जाता है?", options: ['ᱧᱤᱫᱟᱹ (Ninda)', 'ᱥᱮᱛᱟᱜ (Setag)', 'ᱛᱤᱠᱤᱱ (Tikin)', 'ᱟᱹᱭᱩᱵ (Ayub)'], correctIndex: 0 },
      },
      {
        id: 'c3_san_5', grade: '3', subject: 'language_santhali',
        titleHindi: 'वाक्य: "Abo daka bon jomeda"', titleEnglish: 'We are eating food',
        nameHo: 'Abu mandi jomtana', nameSanthali: 'Abo daka bon jomeda', nameMundari: 'Abu mandi jomtana',
        scriptHo: 'Mandi Jom', scriptSanthali: 'ᱟᱵᱚ ᱫᱟᱠᱟ ᱵᱚᱱ ᱡᱚᱢᱮᱫᱟ', scriptMundari: 'हम खाना खा रहे हैं',
        category: 'Sentences', emoji: '🍛', audioClipKey: 'audio_eat_san',
        quizOptions: { questionText: "'हम सब खाना खा रहे हैं' का संथाली अनुवाद क्या है?", options: ['ᱟᱵᱚ ᱫᱟᱠᱟ ᱵᱚᱱ ᱡᱚᱢᱮᱫᱟ', 'ᱟᱵᱚ ᱟᱥᱲᱟ ᱪᱟᱞᱟᱜ', 'ᱟᱵᱚ ᱫᱟᱨᱮ ᱞᱟᱜᱟᱣ', 'ᱟᱵᱚ ᱮᱱᱮᱡ'], correctIndex: 0 },
      },
    ],
    language_mundari: [
      {
        id: 'c3_mun_1', grade: '3', subject: 'language_mundari',
        titleHindi: 'सरहुल पर्व (Sarhul / Baha)', titleEnglish: 'Sarhul Festival',
        nameHo: 'Baha', nameSanthali: 'Baha', nameMundari: 'Sarhul / Baha (सरहुल)',
        scriptHo: '𑢷𑣁𑢹𑣁', scriptSanthali: 'ᱵᱟᱦᱟ', scriptMundari: 'सरहुल',
        category: 'Festivals', emoji: '🌸', audioClipKey: 'audio_sarhul',
        quizOptions: { questionText: "मुंडा समाज में वसंत ऋतु में सखुआ फूल की पूजा का पर्व क्या कहलाता है?", options: ['सरहुल (Sarhul / Baha)', 'सोहराय', 'करमा', 'मागे'], correctIndex: 0 },
      },
      {
        id: 'c3_mun_2', grade: '3', subject: 'language_mundari',
        titleHindi: 'करमा पर्व (Karma Parab)', titleEnglish: 'Karma Festival',
        nameHo: 'Karma', nameSanthali: 'Karam', nameMundari: 'Karma (करमा)',
        scriptHo: '𑢢𑣁𑣜𑣭𑣁', scriptSanthali: 'ᱠᱟᱨᱟᱢ', scriptMundari: 'करमा',
        category: 'Festivals', emoji: '🌿', audioClipKey: 'audio_karma',
        quizOptions: { questionText: "प्रकृति व कर्म की पूजा का पर्व 'करमा' में किस वृक्ष की डाली लगाई जाती है?", options: ['करम वृक्ष (Karam Tree)', 'आम', 'नीम', 'बरगद'], correctIndex: 0 },
      },
      {
        id: 'c3_mun_3', grade: '3', subject: 'language_mundari',
        titleHindi: 'पक्षी (Bird - Chetan / Chene)', titleEnglish: 'Bird',
        nameHo: 'Chene', nameSanthali: 'Chene', nameMundari: 'Chene (चेने)',
        scriptHo: '𑢮𑣈𑣓𑣈', scriptSanthali: 'ᱪᱮᱬᱮ', scriptMundari: 'चेने',
        category: 'Animals', emoji: '🦜', audioClipKey: 'audio_bird_mun',
        quizOptions: { questionText: "मुंडारी में 'पक्षी/चिड़िया' को क्या कहते हैं?", options: ['चेने (Chene)', 'हाई (Hai)', 'उरी (Uri)', 'सेता (Seta)'], correctIndex: 0 },
      },
      {
        id: 'c3_mun_4', grade: '3', subject: 'language_mundari',
        titleHindi: 'सवेरा (Morning - Seta)', titleEnglish: 'Morning',
        nameHo: 'Seta', nameSanthali: 'Setag', nameMundari: 'Seta (सेताः)',
        scriptHo: '𑢝𑣈𑣕𑣁', scriptSanthali: 'ᱥᱮᱛᱟᱜ', scriptMundari: 'सेताः',
        category: 'Time', emoji: '🌅', audioClipKey: 'audio_seta_mun',
        quizOptions: { questionText: "मुंडारी में 'सुबह' को क्या कहते हैं?", options: ['सेताः (Seta)', 'अयूब (Ayub)', 'निदाः (Nida)', 'तिकली'], correctIndex: 0 },
      },
      {
        id: 'c3_mun_5', grade: '3', subject: 'language_mundari',
        titleHindi: 'वाक्य: "Aing iskul senotana"', titleEnglish: 'I am going to school',
        nameHo: 'Aing iskul senotana', nameSanthali: 'Ing asra tebon chalao-a', nameMundari: 'Aing iskul senotana (आईंग इस्कुल सेनोतना)',
        scriptHo: 'Iskul Sen', scriptSanthali: 'ᱟᱥᱲᱟ ᱪᱟᱞᱟᱜ', scriptMundari: 'मैं स्कूल जा रहा हूँ',
        category: 'Sentences', emoji: '🚶‍♂️', audioClipKey: 'audio_sent_mun',
        quizOptions: { questionText: "'मैं विद्यालय जा रहा हूँ' को मुंडारी में क्या कहते हैं?", options: ['Aing iskul senotana', 'Aing mandi jomtana', 'Aing da nuyetana', 'Aing inungtana'], correctIndex: 0 },
      },
    ],
    math: [
      {
        id: 'c3_math_1', grade: '3', subject: 'math',
        titleHindi: 'गुणा: 6 × 7 = 42', titleEnglish: 'Multiplication: 6 × 7',
        nameHo: 'Guna', nameSanthali: 'Guna', nameMundari: 'Guna',
        scriptHo: '6 × 7 = 42', scriptSanthali: '6 × 7 = 42', scriptMundari: '६ × ७ = ४२',
        category: 'Multiplication', emoji: '✖️', audioClipKey: 'audio_mul',
        quizOptions: { questionText: "६ × ७ का गुणनफल क्या होगा?", options: ['४२ (Forty-Two)', '३६ (Thirty-Six)', '४८ (Forty-Eight)', '४० (Forty)'], correctIndex: 0 },
      },
      {
        id: 'c3_math_2', grade: '3', subject: 'math',
        titleHindi: 'भाग: 36 ÷ 6 = 6', titleEnglish: 'Division: 36 ÷ 6',
        nameHo: 'Hating', nameSanthali: 'Hating', nameMundari: 'Hating',
        scriptHo: '36 ÷ 6 = 6', scriptSanthali: '36 ÷ 6 = 6', scriptMundari: '३६ ÷ ६ = ६',
        category: 'Division', emoji: '➗', audioClipKey: 'audio_div',
        quizOptions: { questionText: "३६ को ६ से भाग देने पर भागफल क्या होगा?", options: ['६ (Six)', '७ (Seven)', '५ (Five)', '८ (Eight)'], correctIndex: 0 },
      },
      {
        id: 'c3_math_3', grade: '3', subject: 'math',
        titleHindi: 'भिन्न: 1/4 (One-Fourth)', titleEnglish: 'Fraction 1/4',
        nameHo: 'Fraction 1/4', nameSanthali: 'Fraction 1/4', nameMundari: '१/४',
        scriptHo: '1/4', scriptSanthali: '1/4', scriptMundari: '१/४',
        category: 'Fractions', emoji: '🍰', audioClipKey: 'audio_frac',
        quizOptions: { questionText: "१ रोटी के ४ बराबर भागों में से १ भाग को क्या कहेंगे?", options: ['१/४ (एक-चौथाई)', '१/२ (आधा)', '३/४ (तीन-चौथाई)', '१/१ (पूरा)'], correctIndex: 0 },
      },
      {
        id: 'c3_math_4', grade: '3', subject: 'math',
        titleHindi: 'मापन: 1 मीटर = 100 सेमी', titleEnglish: '1 Meter = 100 cm',
        nameHo: '1 m = 100 cm', nameSanthali: '1 m = 100 cm', nameMundari: '१ मी = १०० सेमी',
        scriptHo: '1 m = 100 cm', scriptSanthali: '1 m = 100 cm', scriptMundari: '१०० सेमी',
        category: 'Measurement', emoji: '📏', audioClipKey: 'audio_measure',
        quizOptions: { questionText: "१ मीटर में कितने सेंटीमीटर (cm) होते हैं?", options: ['१०० सेमी (100 cm)', '१० सेमी (10 cm)', '१००० सेमी (1000 cm)', '५० सेमी (50 cm)'], correctIndex: 0 },
      },
      {
        id: 'c3_math_5', grade: '3', subject: 'math',
        titleHindi: 'भार: 1 किग्रा = 1000 ग्राम', titleEnglish: '1 kg = 1000 g',
        nameHo: '1 kg = 1000 g', nameSanthali: '1 kg = 1000 g', nameMundari: '१ किग्रा = १००० ग्राम',
        scriptHo: '1000 g', scriptSanthali: '1000 g', scriptMundari: '१००० ग्राम',
        category: 'Weight', emoji: '⚖️', audioClipKey: 'audio_weight',
        quizOptions: { questionText: "१ किलोग्राम (kg) में कितने ग्राम होते हैं?", options: ['१००० ग्राम (1000 g)', '१०० ग्राम (100 g)', '५०० ग्राम (500 g)', '२००० ग्राम (2000 g)'], correctIndex: 0 },
      },
    ],
    english: [
      {
        id: 'c3_eng_1', grade: '3', subject: 'english',
        titleHindi: 'Noun: Person, Place, Thing', titleEnglish: 'Noun Definition',
        nameHo: 'Nutum (नाम)', nameSanthali: 'Nutum (ᱧᱩᱛᱩᱢ)', nameMundari: 'Nutum (नाम)',
        scriptHo: 'Noun', scriptSanthali: 'ᱧᱩᱛᱩᱢ', scriptMundari: 'संज्ञा',
        category: 'Grammar', emoji: '👦', audioClipKey: 'audio_noun',
        quizOptions: { questionText: "Which word is a Noun in: 'The boy plays with a ball'?", options: ['Boy / Ball', 'Plays', 'With', 'The'], correctIndex: 0 },
      },
      {
        id: 'c3_eng_2', grade: '3', subject: 'english',
        titleHindi: 'Pronoun: He, She, It, They', titleEnglish: 'Pronoun',
        nameHo: 'Pronoun', nameSanthali: 'Pronoun', nameMundari: 'सर्वनाम',
        scriptHo: 'Pronoun', scriptSanthali: 'Pronoun', scriptMundari: 'सर्वनाम',
        category: 'Grammar', emoji: '🔄', audioClipKey: 'audio_pronoun',
        quizOptions: { questionText: "Which word is a Pronoun replacing 'Ravi'?", options: ['He', 'She', 'It', 'They'], correctIndex: 0 },
      },
      {
        id: 'c3_eng_3', grade: '3', subject: 'english',
        titleHindi: 'Opposites: Big ↔ Small', titleEnglish: 'Opposites',
        nameHo: 'Marang ↔ Hurin', nameSanthali: 'Marang ↔ Katih', nameMundari: 'Marang ↔ Hudin',
        scriptHo: 'Big / Small', scriptSanthali: 'ᱢᱟᱨᱟᱝ / ᱠᱟᱹᱴᱤᱡ', scriptMundari: 'बड़ा / छोटा',
        category: 'Vocabulary', emoji: '⬆️⬇️', audioClipKey: 'audio_opp',
        quizOptions: { questionText: "What is the opposite of 'Big'?", options: ['Small', 'Huge', 'Large', 'Tall'], correctIndex: 0 },
      },
      {
        id: 'c3_eng_4', grade: '3', subject: 'english',
        titleHindi: 'Adjective: Beautiful, Green', titleEnglish: 'Adjective',
        nameHo: 'Bugi / Haria', nameSanthali: 'Bogi / Hariyad', nameMundari: 'Bugi / Haria',
        scriptHo: 'Adjective', scriptSanthali: 'Adjective', scriptMundari: 'विशेषण',
        category: 'Grammar', emoji: '🟢', audioClipKey: 'audio_adj',
        quizOptions: { questionText: "Which word is an Adjective in: 'It is a green leaf'?", options: ['Green', 'Leaf', 'It', 'Is'], correctIndex: 0 },
      },
      {
        id: 'c3_eng_5', grade: '3', subject: 'english',
        titleHindi: 'Question Word: What & Where', titleEnglish: 'Question Words',
        nameHo: 'Chikana / Okore', nameSanthali: 'Chet / Okare', nameMundari: 'Chikan / Okare',
        scriptHo: 'What / Where', scriptSanthali: 'ᱪᱮᱫ / ᱚᱠᱟᱨᱮ', scriptMundari: 'क्या / कहाँ',
        category: 'Questions', emoji: '❓', audioClipKey: 'audio_q_words',
        quizOptions: { questionText: "Which question word asks about a place?", options: ['Where', 'What', 'Who', 'When'], correctIndex: 0 },
      },
    ],
    science: [],
    hindi: [],
  },

  // =========================================================================
  // CLASS 4 (5 Cards per Subject)
  // =========================================================================
  '4': {
    evs: [
      {
        id: 'c4_evs_1', grade: '4', subject: 'evs',
        titleHindi: 'मानव हृदय (Human Heart)', titleEnglish: 'Human Heart',
        nameHo: 'Mayom Pump', nameSanthali: 'Mayom Pump', nameMundari: 'Mayom Pump',
        scriptHo: 'Heart', scriptSanthali: 'Heart', scriptMundari: 'हृदय',
        category: 'Human Body', emoji: '❤️', audioClipKey: 'audio_heart',
        quizOptions: { questionText: "मानव शरीर में रक्त को पूरे शरीर में कौन पंप करता है?", options: ['हृदय (Heart)', 'फेफड़े (Lungs)', 'आमाशय (Stomach)', 'मस्तिष्क (Brain)'], correctIndex: 0 },
      },
      {
        id: 'c4_evs_2', grade: '4', subject: 'evs',
        titleHindi: 'कोयला खनिज (Coal Resource)', titleEnglish: 'Coal Mineral',
        nameHo: 'Koyla', nameSanthali: 'Koyla', nameMundari: 'Koyla',
        scriptHo: 'Coal', scriptSanthali: 'Coal', scriptMundari: 'कोयला',
        category: 'Minerals', emoji: '🪨', audioClipKey: 'audio_coal',
        quizOptions: { questionText: "झारखंड के झरिया और धनबाद किस प्रमुख खनिज के लिए प्रसिद्ध हैं?", options: ['कोयला (Coal)', 'सोना (Gold)', 'हीरा (Diamond)', 'पेट्रोलियम'], correctIndex: 0 },
      },
      {
        id: 'c4_evs_3', grade: '4', subject: 'evs',
        titleHindi: 'दलमा वन्यजीव अभयारण्य (Dalma Wildlife)', titleEnglish: 'Dalma Sanctuary',
        nameHo: 'Dalma Sanctuary', nameSanthali: 'Dalma Sanctuary', nameMundari: 'दलमा अभयारण्य',
        scriptHo: 'Dalma', scriptSanthali: 'Dalma', scriptMundari: 'दलमा',
        category: 'Wildlife', emoji: '🐘', audioClipKey: 'audio_dalma',
        quizOptions: { questionText: "दलमा वन्यजीव अभयारण्य मुख्य रूप से किस पशु के लिए जाना जाता है?", options: ['एशियाई हाथी (Elephant)', 'शेर (Lion)', 'गैंडा (Rhino)', 'ऊँट (Camel)'], correctIndex: 0 },
      },
      {
        id: 'c4_evs_4', grade: '4', subject: 'evs',
        titleHindi: 'सड़क सुरक्षा संकेत (Traffic Safety)', titleEnglish: 'Traffic Safety',
        nameHo: 'Safety Rules', nameSanthali: 'Safety Rules', nameMundari: 'सुरक्षा नियम',
        scriptHo: 'Safety', scriptSanthali: 'Safety', scriptMundari: 'सुरक्षा',
        category: 'Safety', emoji: '🚦', audioClipKey: 'audio_safety',
        quizOptions: { questionText: "ट्रैफिक सिग्नल पर लाल बत्ती (Red Light) का क्या अर्थ है?", options: ['रुकिए (Stop)', 'चलिए (Go)', 'दौड़िए (Run)', 'मुड़िए (Turn)'], correctIndex: 0 },
      },
      {
        id: 'c4_evs_5', grade: '4', subject: 'evs',
        titleHindi: 'भगवान बिरसा मुंडा (Birsa Munda)', titleEnglish: 'Birsa Munda',
        nameHo: 'Birsa Munda', nameSanthali: 'Birsa Munda', nameMundari: 'बिरसा मुंडा',
        scriptHo: 'Birsa Munda', scriptSanthali: 'Birsa Munda', scriptMundari: 'बिरसा मुंडा',
        category: 'History', emoji: '🏹', audioClipKey: 'audio_birsa',
        quizOptions: { questionText: "भगवान बिरसा मुंडा ने जल-जंगल-जमीन की रक्षा के लिए किस आंदोलन का नेतृत्व किया?", options: ['उलगुलान क्रांति (Ulgulan)', 'चिपको आंदोलन', 'असहयोग आंदोलन', 'भारत छोड़ो'], correctIndex: 0 },
      },
    ],
    language_ho: [
      {
        id: 'c4_ho_1', grade: '4', subject: 'language_ho',
        titleHindi: 'सिधो-कान्हू हुल (Santhal & Tribal Hool)', titleEnglish: 'Tribal Resistance',
        nameHo: 'Sidho-Kanhu Hool', nameSanthali: 'Sidho-Kanhu Hool', nameMundari: 'Hool',
        scriptHo: '𑢝𑣂𑢵𑣉-𑢢𑣁𑣓𑣹𑣉', scriptSanthali: 'ᱥᱤᱫᱷᱳ-ᱠᱟᱹᱱᱦᱩ', scriptMundari: 'सिधो कान्हू',
        category: 'History & Culture', emoji: '🏹', audioClipKey: 'audio_hool',
        quizOptions: { questionText: "1855 के प्रसिद्ध संताल हुल क्रांति के महानायक कौन थे?", options: ['सिधो-कान्हू व चांद-भैरव', 'मंगल पांडे', 'भगत सिंह', 'तात्या टोपे'], correctIndex: 0 },
      },
      {
        id: 'c4_ho_2', grade: '4', subject: 'language_ho',
        titleHindi: 'महुआ वृक्ष (Matkom / Mahua)', titleEnglish: 'Mahua Tree',
        nameHo: 'Matkom (मातकोम)', nameSanthali: 'Matkom (ᱢᱟᱛᱠᱳᱢ)', nameMundari: 'Madkam',
        scriptHo: '𑢭𑣁𑣕𑢢𑣉𑣭', scriptSanthali: 'ᱢᱟᱛᱠᱳᱢ', scriptMundari: 'मातकोम',
        category: 'Flora & Heritage', emoji: '🌿', audioClipKey: 'audio_matkom',
        quizOptions: { questionText: "हो व संथाली में 'महुआ' के पेड़ को क्या कहते हैं?", options: ['Matkom (मातकोम)', 'Sarjom (सखुआ)', 'Dare', 'Kode'], correctIndex: 0 },
      },
      {
        id: 'c4_ho_3', grade: '4', subject: 'language_ho',
        titleHindi: 'भूतकाल क्रिया (Past Tense - Senkena)', titleEnglish: 'Past Tense',
        nameHo: 'Senkena (गया था)', nameSanthali: 'Senlenae', nameMundari: 'Senkena',
        scriptHo: '𑢝𑣈𑣓𑢢𑣈𑣓𑣁', scriptSanthali: 'ᱥᱮᱱᱞᱮᱱᱟᱭ', scriptMundari: 'सेनकेना',
        category: 'Grammar', emoji: '⏳', audioClipKey: 'audio_past_ho',
        quizOptions: { questionText: "'वह विद्यालय गया था' को हो भाषा में क्या कहते हैं?", options: ['Aini iskul senkena', 'Aini iskul senotana', 'Aini iskul sena', 'Aini iskul ol'], correctIndex: 0 },
      },
      {
        id: 'c4_ho_4', grade: '4', subject: 'language_ho',
        titleHindi: 'लोकोक्ति व कहावतें (Ho Proverbs)', titleEnglish: 'Proverbs',
        nameHo: 'Bugi Kaji / Kahani', nameSanthali: 'Katha', nameMundari: 'Kahani',
        scriptHo: '𑢷𑣉𑢩𑣂 𑢢𑣁𑢯𑣂', scriptSanthali: 'ᱠᱟᱛᱷᱟ', scriptMundari: 'कहावत',
        category: 'Literature', emoji: '📜', audioClipKey: 'audio_proverbs',
        quizOptions: { questionText: "पारंपरिक ज्ञान व शिक्षा देने वाली कथाओं को क्या कहा जाता है?", options: ['लोककथा / लोकोक्ति', 'संवाद', 'पत्र', 'नाटक'], correctIndex: 0 },
      },
      {
        id: 'c4_ho_5', grade: '4', subject: 'language_ho',
        titleHindi: 'प्रकृति संरक्षण (Forest Conservation)', titleEnglish: 'Nature Conservation',
        nameHo: 'Bir Banchao', nameSanthali: 'Bir Banchao', nameMundari: 'Bir Banchao',
        scriptHo: '𑢷𑣂𑣜 𑢷𑣁𑣓𑢮𑣁𑣉', scriptSanthali: 'ᱵᱤᱨ ᱵᱟᱧᱪᱟᱣ', scriptMundari: 'बीर बचाओ',
        category: 'Environment', emoji: '🌲', audioClipKey: 'audio_bir_save',
        quizOptions: { questionText: "हो भाषा में 'जंगल बचाओ' को क्या कहते हैं?", options: ['Bir Banchao (बीर बचाओ)', 'Da Nuyen', 'Hatu Sen', 'Mandi Jom'], correctIndex: 0 },
      },
    ],
    language_santhali: [
      {
        id: 'c4_san_1', grade: '4', subject: 'language_santhali',
        titleHindi: 'संताल हुल (Santhal Hool 1855)', titleEnglish: 'Santhal Hool',
        nameHo: 'Santhal Hool', nameSanthali: 'Santhal Hool (ᱥᱟᱱᱛᱷᱟᱞ ᱦᱩᱞ)', nameMundari: 'Hool',
        scriptHo: 'Hool', scriptSanthali: 'ᱥᱟᱱᱛᱷᱟᱞ ᱦᱩᱞ', scriptMundari: 'संताल हुल',
        category: 'History', emoji: '🏹', audioClipKey: 'audio_san_hool',
        quizOptions: { questionText: "संताली में 'क्रांति/विद्रोह' को क्या कहा जाता है?", options: ['ᱦᱩᱞ (Hool)', 'ᱮᱱᱮᱡ (Enech)', 'ᱥᱮᱨᱮᱧ (Sereng)', 'ᱯᱟᱲᱦᱟᱣ (Parhao)'], correctIndex: 0 },
      },
      {
        id: 'c4_san_2', grade: '4', subject: 'language_santhali',
        titleHindi: 'पंडित रघुनाथ मुर्मू (Pt. Raghunath Murmu)', titleEnglish: 'Pt. Raghunath Murmu',
        nameHo: 'Pt Raghunath Murmu', nameSanthali: 'Pt Raghunath Murmu (ᱯᱚᱸᱰᱮᱛ ᱨᱟᱹᱜᱷᱩᱱᱟᱛᱷ ᱢᱩᱨᱢᱩ)', nameMundari: 'रघुनाथ मुर्मू',
        scriptHo: 'Raghunath Murmu', scriptSanthali: 'ᱯᱚᱸᱰᱮᱛ ᱨᱟᱹᱜᱷᱩᱱᱟᱛᱷ ᱢᱩᱨᱢᱩ', scriptMundari: 'पंडित रघुनाथ मुर्मू',
        category: 'Script Creator', emoji: '📜', audioClipKey: 'audio_murmu',
        quizOptions: { questionText: "1925 में संथाली भाषा की 'ओल चिकी' लिपि का आविष्कार किसने किया?", options: ['पंडित रघुनाथ मुर्मू (Pt Raghunath Murmu)', 'बिरसा मुंडा', 'सिधो-कान्हू', 'तिलका मांझी'], correctIndex: 0 },
      },
      {
        id: 'c4_san_3', grade: '4', subject: 'language_santhali',
        titleHindi: 'भूतकाल क्रिया (Past Tense - Santhali)', titleEnglish: 'Past Tense',
        nameHo: 'Senkena', nameSanthali: 'Senlenae (ᱥᱮᱱᱞᱮᱱᱟᱭ)', nameMundari: 'Senkena',
        scriptHo: 'Past', scriptSanthali: 'ᱥᱮᱱᱞᱮᱱᱟᱭ', scriptMundari: 'भूतकाल',
        category: 'Grammar', emoji: '⏳', audioClipKey: 'audio_past_san',
        quizOptions: { questionText: "'वह गया था' को संथाली (Ol Chiki) में क्या कहते हैं?", options: ['ᱥᱮᱱᱞᱮᱱᱟᱭ (Senlenae)', 'ᱪᱟᱞᱟᱜ ᱠᱟᱱᱟᱭ', 'ᱪᱟᱞᱟᱜ-ᱟᱭ', 'ᱡᱚᱢᱮᱫᱟᱭ'], correctIndex: 0 },
      },
      {
        id: 'c4_san_4', grade: '4', subject: 'language_santhali',
        titleHindi: 'संताली लोकोक्ति (Santhali Proverbs)', titleEnglish: 'Proverbs',
        nameHo: 'Proverbs', nameSanthali: 'Men Katha (ᱢᱮᱱ ᱠᱟᱛᱷᱟ)', nameMundari: 'कहावत',
        scriptHo: 'Proverbs', scriptSanthali: 'ᱢᱮᱱ ᱠᱟᱛᱷᱟ', scriptMundari: 'कहावत',
        category: 'Literature', emoji: '📖', audioClipKey: 'audio_men_katha',
        quizOptions: { questionText: "संथाली में कहावतों को क्या कहा जाता है?", options: ['ᱢᱮᱱ ᱠᱟᱛᱷᱟ (Men Katha)', 'ᱥᱮᱨᱮᱧ', 'ᱮᱱᱮᱡ', 'ᱯᱩᱛᱷᱤ'], correctIndex: 0 },
      },
      {
        id: 'c4_san_5', grade: '4', subject: 'language_santhali',
        titleHindi: 'वन संरक्षण (Bir Banchao)', titleEnglish: 'Forest Conservation',
        nameHo: 'Bir Banchao', nameSanthali: 'Bir Banchao (ᱵᱤᱨ ᱵᱟᱧᱪᱟᱣ)', nameMundari: 'Bir Banchao',
        scriptHo: 'Bir Banchao', scriptSanthali: 'ᱵᱤᱨ ᱵᱟᱧᱪᱟᱣ', scriptMundari: 'बीर बचाओ',
        category: 'Ecology', emoji: '🌲', audioClipKey: 'audio_bir_san',
        quizOptions: { questionText: "संथाली में 'वनों की रक्षा करो' का नारा क्या है?", options: ['ᱵᱤᱨ ᱵᱟᱧᱪᱟᱣ (Bir Banchao)', 'ᱫᱟᱨᱮ ᱜᱮᱫ', 'ᱫᱟᱜ ᱧᱩ', 'ᱟᱥᱲᱟ ᱪᱟᱞᱟᱜ'], correctIndex: 0 },
      },
    ],
    language_mundari: [
      {
        id: 'c4_mun_1', grade: '4', subject: 'language_mundari',
        titleHindi: 'बिरसा मुंडा उलगुलान (Ulgulan Revolution)', titleEnglish: 'Ulgulan Revolution',
        nameHo: 'Ulgulan', nameSanthali: 'Hool', nameMundari: 'Ulgulan (उलगुलान क्रांति)',
        scriptHo: 'Ulgulan', scriptSanthali: 'ᱦᱩᱞ', scriptMundari: 'उलगुलान',
        category: 'History', emoji: '🏹', audioClipKey: 'audio_ulgulan',
        quizOptions: { questionText: "मुंडा विद्रोह का ऐतिहासिक नाम क्या था?", options: ['उलगुलान क्रांति (Ulgulan)', 'चिपको', 'सत्याग्रह', 'भारत छोड़ो'], correctIndex: 0 },
      },
      {
        id: 'c4_mun_2', grade: '4', subject: 'language_mundari',
        titleHindi: 'सखुआ वन (Sarjom Bir)', titleEnglish: 'Sal Forest',
        nameHo: 'Sarjom Bir', nameSanthali: 'Sarjom Bir', nameMundari: 'Sarjom Bir (सरजोम बीर)',
        scriptHo: 'Sarjom Bir', scriptSanthali: 'ᱥᱟᱨᱡᱚᱢ ᱵᱤᱨ', scriptMundari: 'सरजोम बीर',
        category: 'Heritage', emoji: '🌳', audioClipKey: 'audio_sarjom_bir',
        quizOptions: { questionText: "मुंडारी में 'साल के जंगल' को क्या कहते हैं?", options: ['सरजोम बीर (Sarjom Bir)', 'दारू गाडा', 'हासा बुरु', 'ओड़ाः'], correctIndex: 0 },
      },
      {
        id: 'c4_mun_3', grade: '4', subject: 'language_mundari',
        titleHindi: 'भूतकाल क्रिया (Past Tense - Mundari)', titleEnglish: 'Past Tense',
        nameHo: 'Senkena', nameSanthali: 'Senlenae', nameMundari: 'Senkena (सेनकेना)',
        scriptHo: 'Senkena', scriptSanthali: 'Senlenae', scriptMundari: 'सेनकेना',
        category: 'Grammar', emoji: '⏳', audioClipKey: 'audio_past_mun',
        quizOptions: { questionText: "'मैं कल बाजार गया था' को मुंडारी में क्या कहेंगे?", options: ['Aing hola hath senkena', 'Aing tisin hath senotana', 'Aing gapa sena', 'Aing mandi jomtana'], correctIndex: 0 },
      },
      {
        id: 'c4_mun_4', grade: '4', subject: 'language_mundari',
        titleHindi: 'मुंडारी लोकगीत (Mundari Folk Song)', titleEnglish: 'Folk Song',
        nameHo: 'Durang', nameSanthali: 'Sereng', nameMundari: 'Mundari Durang (दुरंग)',
        scriptHo: 'Durang', scriptSanthali: 'ᱥᱮᱨᱮᱧ', scriptMundari: 'दुरंग',
        category: 'Music', emoji: '🎵', audioClipKey: 'audio_mun_durang',
        quizOptions: { questionText: "मुंडा संस्कृति में ऋतु गीतों को क्या कहते हैं?", options: ['दुरंग (Durang)', 'काजी', 'ओल', 'पड़ाव'], correctIndex: 0 },
      },
      {
        id: 'c4_mun_5', grade: '4', subject: 'language_mundari',
        titleHindi: 'सरना धर्म स्थल (Sarna Sthal)', titleEnglish: 'Sarna Sacred Grove',
        nameHo: 'Sarna', nameSanthali: 'Jaher Than', nameMundari: 'Sarna / Jaher (सरना स्थल)',
        scriptHo: 'Sarna', scriptSanthali: 'ᱡᱟᱦᱮᱨ ᱛᱷᱟᱱ', scriptMundari: 'सरना स्थल',
        category: 'Sacred Sites', emoji: '🏛️', audioClipKey: 'audio_sarna',
        quizOptions: { questionText: "आदिवासी समाज का पारंपरिक पूजा स्थल जहाँ प्रकृति की पूजा होती है:", options: ['सरना स्थल / जाहेर थान', 'किला', 'भवन', 'सभागार'], correctIndex: 0 },
      },
    ],
    math: [
      {
        id: 'c4_math_1', grade: '4', subject: 'math',
        titleHindi: 'भिन्न जोड़: 2/7 + 3/7 = 5/7', titleEnglish: 'Fraction Addition',
        nameHo: 'Fraction Misa', nameSanthali: 'Fraction Mesawa', nameMundari: 'Fraction Juma',
        scriptHo: '2/7 + 3/7 = 5/7', scriptSanthali: '2/7 + 3/7 = 5/7', scriptMundari: '२/७ + ३/७ = ५/७',
        category: 'Fractions', emoji: '🍰', audioClipKey: 'audio_frac_add',
        quizOptions: { questionText: "२/७ + ३/७ का सही मान क्या होगा?", options: ['५/७ (Five-Sevenths)', '५/१४', '६/७', '१/७'], correctIndex: 0 },
      },
      {
        id: 'c4_math_2', grade: '4', subject: 'math',
        titleHindi: 'दशमलव: 2.5 + 1.25 = 3.75', titleEnglish: 'Decimals Addition',
        nameHo: 'Decimal Misa', nameSanthali: 'Decimal Mesawa', nameMundari: 'Decimal Juma',
        scriptHo: '2.5 + 1.25 = 3.75', scriptSanthali: '2.5 + 1.25 = 3.75', scriptMundari: '२.५ + १.२५ = ३.७५',
        category: 'Decimals', emoji: '🔢', audioClipKey: 'audio_dec',
        quizOptions: { questionText: "२.५ + १.२५ का योग क्या होगा?", options: ['३.७५ (3.75)', '३.५० (3.50)', '४.०० (4.00)', '२.७५ (2.75)'], correctIndex: 0 },
      },
      {
        id: 'c4_math_3', grade: '4', subject: 'math',
        titleHindi: 'आयत परिमाप = 2 × (L + B)', titleEnglish: 'Perimeter',
        nameHo: 'Rectangle Gherao', nameSanthali: 'Rectangle Gherao', nameMundari: 'आयत परिमाप',
        scriptHo: '2 × (L + B)', scriptSanthali: '2 × (L + B)', scriptMundari: '२ × (L + B)',
        category: 'Geometry', emoji: '📐', audioClipKey: 'audio_perimeter',
        quizOptions: { questionText: "लंबाई = 6 सेमी, चौड़ाई = 4 सेमी वाले आयत का परिमाप क्या होगा?", options: ['२० सेमी (20 cm)', '२४ सेमी (24 cm)', '१० सेमी (10 cm)', '१२ सेमी (12 cm)'], correctIndex: 0 },
      },
      {
        id: 'c4_math_4', grade: '4', subject: 'math',
        titleHindi: 'समकोण = 90° (Right Angle)', titleEnglish: 'Right Angle',
        nameHo: '90° Angle', nameSanthali: '90° Angle', nameMundari: '९०° समकोण',
        scriptHo: '90°', scriptSanthali: '90°', scriptMundari: '९०°',
        category: 'Angles', emoji: '📐', audioClipKey: 'audio_angle',
        quizOptions: { questionText: "समकोण (Right Angle) का माप कितना होता है?", options: ['९०° (90 Degrees)', '४५° (45 Degrees)', '१८०° (180 Degrees)', '३६०° (360 Degrees)'], correctIndex: 0 },
      },
      {
        id: 'c4_math_5', grade: '4', subject: 'math',
        titleHindi: 'ऐकिक नियम: 5 × ₹40 = ₹200', titleEnglish: 'Unitary Method',
        nameHo: 'Unitary', nameSanthali: 'Unitary', nameMundari: 'ऐकिक नियम',
        scriptHo: '5 × 40 = 200', scriptSanthali: '5 × 40 = 200', scriptMundari: '५ × ४० = ₹२००',
        category: 'Word Problems', emoji: '🛒', audioClipKey: 'audio_word_prob',
        quizOptions: { questionText: "१ किलो चावल का मूल्य ₹४० है, तो ५ किलो का मूल्य क्या होगा?", options: ['₹२०० (Rs. 200)', '₹१६० (Rs. 160)', '₹२४० (Rs. 240)', '₹१०० (Rs. 100)'], correctIndex: 0 },
      },
    ],
    english: [
      {
        id: 'c4_eng_1', grade: '4', subject: 'english',
        titleHindi: 'Past Tense: Play ➔ Played', titleEnglish: 'Past Tense',
        nameHo: 'Inungkena', nameSanthali: 'Enechlena', nameMundari: 'Enenkena',
        scriptHo: 'Played', scriptSanthali: 'Played', scriptMundari: 'खेला था',
        category: 'Grammar', emoji: '⏳', audioClipKey: 'audio_played',
        quizOptions: { questionText: "What is the past tense of 'Play'?", options: ['Played', 'Playing', 'Plays', 'Player'], correctIndex: 0 },
      },
      {
        id: 'c4_eng_2', grade: '4', subject: 'english',
        titleHindi: 'Irregular Verb: Go ➔ Went', titleEnglish: 'Irregular Verb',
        nameHo: 'Senkena', nameSanthali: 'Senlena', nameMundari: 'Senkena',
        scriptHo: 'Went', scriptSanthali: 'Went', scriptMundari: 'गया था',
        category: 'Grammar', emoji: '🚶‍♂️', audioClipKey: 'audio_went',
        quizOptions: { questionText: "What is the past tense of 'Go'?", options: ['Went', 'Goed', 'Going', 'Gone'], correctIndex: 0 },
      },
      {
        id: 'c4_eng_3', grade: '4', subject: 'english',
        titleHindi: 'Conjunction: and, but, because', titleEnglish: 'Conjunctions',
        nameHo: 'Conjunction', nameSanthali: 'Conjunction', nameMundari: 'योजक शब्द',
        scriptHo: 'and / but', scriptSanthali: 'and / but', scriptMundari: 'और / लेकिन',
        category: 'Grammar', emoji: '🔗', audioClipKey: 'audio_conj',
        quizOptions: { questionText: "Complete: 'Ravi ran fast _____ he missed the bus.'", options: ['but', 'and', 'or', 'so'], correctIndex: 0 },
      },
      {
        id: 'c4_eng_4', grade: '4', subject: 'english',
        titleHindi: 'Punctuation: Capital Letters & Period', titleEnglish: 'Punctuation',
        nameHo: 'Punctuation', nameSanthali: 'Punctuation', nameMundari: 'विराम चिन्ह',
        scriptHo: 'Capital & .', scriptSanthali: 'Capital & .', scriptMundari: 'विराम चिन्ह',
        category: 'Writing', emoji: '🔤', audioClipKey: 'audio_punct',
        quizOptions: { questionText: "Every English sentence starts with a:", options: ['Capital Letter', 'Small Letter', 'Number', 'Question Mark'], correctIndex: 0 },
      },
      {
        id: 'c4_eng_5', grade: '4', subject: 'english',
        titleHindi: 'Comprehension: Finding the Main Idea', titleEnglish: 'Main Idea',
        nameHo: 'Comprehension', nameSanthali: 'Comprehension', nameMundari: 'मुख्य विचार',
        scriptHo: 'Main Idea', scriptSanthali: 'Main Idea', scriptMundari: 'मुख्य भाव',
        category: 'Reading', emoji: '📖', audioClipKey: 'audio_main_idea',
        quizOptions: { questionText: "The central point that a paragraph explains is called its:", options: ['Main Idea (मुख्य विचार)', 'Title only', 'Punctuation', 'Spelling'], correctIndex: 0 },
      },
    ],
    science: [],
    hindi: [],
  },

  // =========================================================================
  // CLASS 5 (5 Cards per Subject)
  // =========================================================================
  '5': {
    evs: [
      {
        id: 'c5_evs_1', grade: '5', subject: 'evs',
        titleHindi: 'पारिस्थितिकी तंत्र (Ecosystem)', titleEnglish: 'Ecosystem & Producers',
        nameHo: 'Ecosystem', nameSanthali: 'Ecosystem', nameMundari: 'पारिस्थितिकी तंत्र',
        scriptHo: 'Ecosystem', scriptSanthali: 'Ecosystem', scriptMundari: 'पारिस्थितिकी तंत्र',
        category: 'Ecology', emoji: '🌿', audioClipKey: 'audio_eco',
        quizOptions: { questionText: "खाद्य श्रृंखला में प्राथमिक उत्पादक (Primary Producer) कौन होते हैं?", options: ['हरे पेड़-पौधे (Green Plants)', 'शाकाहारी पशु', 'मांसाहारी पशु', 'अपघटक'], correctIndex: 0 },
      },
      {
        id: 'c5_evs_2', grade: '5', subject: 'evs',
        titleHindi: 'सारंडा वन (Saranda - 700 Hills)', titleEnglish: 'Saranda Forest',
        nameHo: 'Saranda Bir', nameSanthali: 'Saranda Bir', nameMundari: 'सारंडा वन',
        scriptHo: 'Saranda', scriptSanthali: 'Saranda', scriptMundari: 'सारंडा',
        category: 'Heritage', emoji: '🌲', audioClipKey: 'audio_saranda',
        quizOptions: { questionText: "एशिया का सबसे बड़ा साल वन 'सारंडा' किस उपनाम से जाना जाता है?", options: ['सात सौ पहाड़ियों की भूमि (700 Hills)', 'झीलों की नगरी', 'कोयला नगरी', 'इस्पात नगरी'], correctIndex: 0 },
      },
      {
        id: 'c5_evs_3', grade: '5', subject: 'evs',
        titleHindi: 'प्रदूषण रोकथाम (Pollution Control)', titleEnglish: 'Pollution Control',
        nameHo: 'Pollution Control', nameSanthali: 'Pollution Control', nameMundari: 'प्रदूषण रोकथाम',
        scriptHo: 'Pollution', scriptSanthali: 'Pollution', scriptMundari: 'प्रदूषण नियंत्रण',
        category: 'Conservation', emoji: '🚯', audioClipKey: 'audio_pollution',
        quizOptions: { questionText: "पर्यावरण प्रदूषण रोकने का सबसे प्रभावी उपाय क्या है?", options: ['अधिक पेड़ लगाना व प्लास्टिक त्यागना', 'कचरा नदी में बहाना', 'पेड़ काटना', 'धुआं फैलाना'], correctIndex: 0 },
      },
      {
        id: 'c5_evs_4', grade: '5', subject: 'evs',
        titleHindi: 'संतुलित आहार (Balanced Diet)', titleEnglish: 'Balanced Diet',
        nameHo: 'Bugi Mandi', nameSanthali: 'Bugi Daka', nameMundari: 'संतुलित आहार',
        scriptHo: 'Balanced Diet', scriptSanthali: 'Balanced Diet', scriptMundari: 'संतुलित आहार',
        category: 'Health', emoji: '🥗', audioClipKey: 'audio_diet',
        quizOptions: { questionText: "शरीर की वृद्धि, मांसपेशियों और मरम्मत के लिए कौन सा पोषक तत्व आवश्यक है?", options: ['प्रोटीन (Protein)', 'वसा (Fat)', 'शर्करा (Sugar)', 'नमक'], correctIndex: 0 },
      },
      {
        id: 'c5_evs_5', grade: '5', subject: 'evs',
        titleHindi: 'सौर ऊर्जा (Solar Energy)', titleEnglish: 'Solar Energy',
        nameHo: 'Singi Shakti', nameSanthali: 'Sin Dare', nameMundari: 'सौर ऊर्जा',
        scriptHo: 'Solar Energy', scriptSanthali: 'Solar Energy', scriptMundari: 'सौर ऊर्जा',
        category: 'Clean Energy', emoji: '☀️', audioClipKey: 'audio_solar',
        quizOptions: { questionText: "सूर्य से प्राप्त होने वाली स्वच्छ और प्रदूषण-मुक्त ऊर्जा क्या कहलाती है?", options: ['सौर ऊर्जा (Solar Energy)', 'कोयला ऊर्जा', 'पेट्रोल', 'डीजल'], correctIndex: 0 },
      },
    ],
    language_ho: [
      {
        id: 'c5_ho_1', grade: '5', subject: 'language_ho',
        titleHindi: 'लाको बोदरा (Lakho Bodra - Script Pioneer)', titleEnglish: 'Lakho Bodra',
        nameHo: 'Guru Kol Lako Bodra', nameSanthali: 'Lakho Bodra', nameMundari: 'लाको बोदरा',
        scriptHo: '𑢚𑣁𑢢𑣉 𑢷𑣉𑢵𑣜𑣁', scriptSanthali: 'Lakho Bodra', scriptMundari: 'लाको बोदरा',
        category: 'Culture & Script', emoji: '📜', audioClipKey: 'audio_bodra',
        quizOptions: { questionText: "हो भाषा की 'वारंग क्षिति' लिपि का पुनरुद्धार किसने किया?", options: ['गुरु कोल लाको बोदरा (Guru Lako Bodra)', 'पंडित रघुनाथ मुर्मू', 'बिरसा मुंडा', 'जयपाल सिंह मुंडा'], correctIndex: 0 },
      },
      {
        id: 'c5_ho_2', grade: '5', subject: 'language_ho',
        titleHindi: 'हो व्याकरण (Ho Advanced Grammar)', titleEnglish: 'Ho Grammar',
        nameHo: 'Ho Vyakaran', nameSanthali: 'Vyakaran', nameMundari: 'व्याकरण',
        scriptHo: '𑢹𑣉 𑢾𑣅𑣁𑢢𑣜𑢰', scriptSanthali: 'Vyakaran', scriptMundari: 'व्याकरण',
        category: 'Advanced Grammar', emoji: '📚', audioClipKey: 'audio_ho_gram',
        quizOptions: { questionText: "हो भाषा में क्रिया रूप किस पर निर्भर करते हैं?", options: ['कर्ता, कर्म व काल (Subject, Object, Tense)', 'केवल संज्ञा', 'केवल लिंग', 'किसी पर नहीं'], correctIndex: 0 },
      },
      {
        id: 'c5_ho_3', grade: '5', subject: 'language_ho',
        titleHindi: 'आदिवासी दर्शन (Tribal Philosophy)', titleEnglish: 'Tribal Philosophy',
        nameHo: 'Prakriti & Horoko', nameSanthali: 'Man & Nature', nameMundari: 'प्रकृति दर्शन',
        scriptHo: '𑢰𑣜𑢢𑣜𑣂𑣕𑣂', scriptSanthali: 'Prakriti', scriptMundari: 'प्रकृति दर्शन',
        category: 'Philosophy', emoji: '🌿', audioClipKey: 'audio_ho_philo',
        quizOptions: { questionText: "आदिवासी जीवन दर्शन का मूल सिद्धांत क्या है?", options: ['प्रकृति के साथ सह-अस्तित्व व संतुलन', 'प्रकृति का दोहन', 'शहरीकरण', 'विनाश'], correctIndex: 0 },
      },
      {
        id: 'c5_ho_4', grade: '5', subject: 'language_ho',
        titleHindi: 'अनुवाद कौशल (Translation Skills)', titleEnglish: 'Translation Skills',
        nameHo: 'Tarjuma Kaji', nameSanthali: 'Tarjuma', nameMundari: 'अनुवाद',
        scriptHo: '𑢕𑣁𑣜𑢯𑣉𑢭𑣁', scriptSanthali: 'Tarjuma', scriptMundari: 'अनुवाद',
        category: 'Linguistics', emoji: '🌐', audioClipKey: 'audio_ho_trans',
        quizOptions: { questionText: "द्विभाषी शिक्षा में मातृभाषा से मानक भाषा सीखने की विधि क्या कहलाती है?", options: ['भाषा सेतु / Voice Bridge', 'रटना', 'मौन पठन', 'अनुकरण'], correctIndex: 0 },
      },
      {
        id: 'c5_ho_5', grade: '5', subject: 'language_ho',
        titleHindi: 'मातृभाषा संरक्षण भाषण (Public Speech)', titleEnglish: 'Mother Tongue Preservation',
        nameHo: 'Bhashan & Kaji', nameSanthali: 'Bhashan', nameMundari: 'भाषण',
        scriptHo: '𑢷𑣁𑢝𑣁𑣓', scriptSanthali: 'Bhashan', scriptMundari: 'भाषण',
        category: 'Oratory', emoji: '🗣️', audioClipKey: 'audio_ho_speech',
        quizOptions: { questionText: "अंतर्राष्ट्रीय मातृभाषा दिवस प्रतिवर्ष कब मनाया जाता है?", options: ['२१ फरवरी (21 February)', '१५ अगस्त', '२६ जनवरी', '५ सितंबर'], correctIndex: 0 },
      },
    ],
    language_santhali: [
      {
        id: 'c5_san_1', grade: '5', subject: 'language_santhali',
        titleHindi: 'संताली साहित्य (Santhali Literature)', titleEnglish: 'Santhali Literature',
        nameHo: 'Literature', nameSanthali: 'Santhali Sahitya (ᱥᱟᱱᱛᱷᱟᱞᱤ ᱥᱟᱦᱤᱛᱭᱚ)', nameMundari: 'साहित्य',
        scriptHo: 'Sahitya', scriptSanthali: 'ᱥᱟᱱᱛᱷᱟᱞᱤ ᱥᱟᱦᱤᱛᱭᱚ', scriptMundari: 'संताली साहित्य',
        category: 'Literature', emoji: '📚', audioClipKey: 'audio_san_lit',
        quizOptions: { questionText: "संथाली भाषा को संविधान की किस अनुसूची में शामिल किया गया है?", options: ['८वीं अनुसूची (8th Schedule - 2003)', '७वीं अनुसूची', '५वीं अनुसूची', '१ली अनुसूची'], correctIndex: 0 },
      },
      {
        id: 'c5_san_2', grade: '5', subject: 'language_santhali',
        titleHindi: 'संताली मुहावरे (Santhali Idioms)', titleEnglish: 'Idioms',
        nameHo: 'Idioms', nameSanthali: 'Bhanit Katha (ᱵᱷᱟᱹᱱᱤᱛ ᱠᱟᱛᱷᱟ)', nameMundari: 'मुहावरे',
        scriptHo: 'Idioms', scriptSanthali: 'ᱵᱷᱟᱹᱱᱤᱛ ᱠᱟᱛᱷᱟ', scriptMundari: 'मुहावरे',
        category: 'Linguistics', emoji: '🎭', audioClipKey: 'audio_san_idioms',
        quizOptions: { questionText: "संथाली में मुहावरों को क्या कहा जाता है?", options: ['ᱵᱷᱟᱹᱱᱤᱛ ᱠᱟᱛᱷᱟ (Bhanit Katha)', 'ᱥᱮᱨᱮᱧ', 'ᱮᱱᱮᱡ', 'ᱚᱞ'], correctIndex: 0 },
      },
      {
        id: 'c5_san_3', grade: '5', subject: 'language_santhali',
        titleHindi: 'संताली लोककथा (Santhali Folklore)', titleEnglish: 'Folklore',
        nameHo: 'Kahani', nameSanthali: 'Karam Kahni (ᱠᱟᱨᱟᱢ ᱠᱟᱹᱦᱱᱤ)', nameMundari: 'लोककथा',
        scriptHo: 'Kahani', scriptSanthali: 'ᱠᱟᱨᱟᱢ ᱠᱟᱹᱦᱱᱤ', scriptMundari: 'लोककथा',
        category: 'Folklore', emoji: '📖', audioClipKey: 'audio_san_folk',
        quizOptions: { questionText: "करमा पर्व के अवसर पर गाई और सुनाई जाने वाली कथा क्या कहलाती है?", options: ['ᱠᱟᱨᱟᱢ ᱠᱟᱹᱦᱱᱤ (Karam Kahni)', 'ᱥᱚᱦᱨᱟᱭ', 'ᱵᱟᱦᱟ', 'ᱫᱟᱥᱟᱸᱭ'], correctIndex: 0 },
      },
      {
        id: 'c5_san_4', grade: '5', subject: 'language_santhali',
        titleHindi: 'अनुवाद कला (Translation in Ol Chiki)', titleEnglish: 'Translation Art',
        nameHo: 'Tarjuma', nameSanthali: 'Tarjuma (ᱛᱚᱨᱡᱚᱢᱟ)', nameMundari: 'अनुवाद',
        scriptHo: 'Tarjuma', scriptSanthali: 'ᱛᱚᱨᱡᱚᱢᱟ', scriptMundari: 'अनुवाद कला',
        category: 'Translation', emoji: '🌐', audioClipKey: 'audio_san_trans',
        quizOptions: { questionText: "संथाली (Ol Chiki) लिपि में अक्षरों की कुल संख्या कितनी है?", options: ['३० अक्षर (30 Letters)', '२६ अक्षर', '५२ अक्षर', '४५ अक्षर'], correctIndex: 0 },
      },
      {
        id: 'c5_san_5', grade: '5', subject: 'language_santhali',
        titleHindi: 'निबंध लेखन (Essay Writing in Santhali)', titleEnglish: 'Essay Writing',
        nameHo: 'Essay', nameSanthali: 'Niban Ol (ᱱᱤᱵᱚᱱ ᱚᱞ)', nameMundari: 'निबंध',
        scriptHo: 'Niban', scriptSanthali: 'ᱱᱤᱵᱚᱱ ᱚᱞ', scriptMundari: 'निबंध लेखन',
        category: 'Creative Writing', emoji: '✍️', audioClipKey: 'audio_san_essay',
        quizOptions: { questionText: "संथाली में रचनात्मक निबंध लेखन को क्या कहते हैं?", options: ['ᱱᱤᱵᱚᱱ ᱚᱞ (Niban Ol)', 'ᱥᱮᱨᱮᱧ', 'ᱮᱱᱮᱡ', 'ᱨᱚᱲ'], correctIndex: 0 },
      },
    ],
    language_mundari: [
      {
        id: 'c5_mun_1', grade: '5', subject: 'language_mundari',
        titleHindi: 'जयपाल सिंह मुंडा (Marang Gomke Jaipal Singh)', titleEnglish: 'Jaipal Singh Munda',
        nameHo: 'Jaipal Singh Munda', nameSanthali: 'Jaipal Singh', nameMundari: 'मारांग गोमके जयपाल सिंह मुंडा',
        scriptHo: 'Jaipal Singh', scriptSanthali: 'Jaipal Singh', scriptMundari: 'जयपाल सिंह मुंडा',
        category: 'Legendary Leaders', emoji: '🏑', audioClipKey: 'audio_jaipal',
        quizOptions: { questionText: "1928 एम्सटर्डम ओलंपिक में भारत को पहला हॉकी स्वर्ण पदक दिलाने वाले मुंडा कप्तान कौन थे?", options: ['मारांग गोमके जयपाल सिंह मुंडा', 'बिरसा मुंडा', 'ध्यानचंद', 'सिधो कान्हू'], correctIndex: 0 },
      },
      {
        id: 'c5_mun_2', grade: '5', subject: 'language_mundari',
        titleHindi: 'मुंडारी व्याकरण (Mundari Grammar Rules)', titleEnglish: 'Mundari Grammar',
        nameHo: 'Grammar', nameSanthali: 'Vyakaran', nameMundari: 'मुंडारी व्याकरण',
        scriptHo: 'Grammar', scriptSanthali: 'Vyakaran', scriptMundari: 'मुंडारी व्याकरण',
        category: 'Grammar', emoji: '📚', audioClipKey: 'audio_mun_gram',
        quizOptions: { questionText: "मुंडारी भाषा किस प्रसिद्ध भाषा परिवार का अंग है?", options: ['ऑस्ट्रो-एशियाटिक / मुंडा परिवार (Austroasiatic)', 'इंडो-आर्यन', 'द्रविड़', 'तिब्बती'], correctIndex: 0 },
      },
      {
        id: 'c5_mun_3', grade: '5', subject: 'language_mundari',
        titleHindi: 'मुंडारी लोक दर्शन (Mundari Ethos)', titleEnglish: 'Mundari Ethos',
        nameHo: 'Philosophy', nameSanthali: 'Philosophy', nameMundari: 'मुंडारी जीवन दर्शन',
        scriptHo: 'Ethos', scriptSanthali: 'Ethos', scriptMundari: 'जीवन दर्शन',
        category: 'Philosophy', emoji: '🌿', audioClipKey: 'audio_mun_philo',
        quizOptions: { questionText: "मुंडा समाज में ग्राम देवता के अधिष्ठाता को क्या कहा जाता है?", options: ['हातु बोंगा / सिंगबोंगा (Singbonga)', 'राजा', 'मुखिया', 'माचेत'], correctIndex: 0 },
      },
      {
        id: 'c5_mun_4', grade: '5', subject: 'language_mundari',
        titleHindi: 'द्विभाषी अनुवाद (Dual Translation)', titleEnglish: 'Translation',
        nameHo: 'Tarjuma', nameSanthali: 'Tarjuma', nameMundari: 'द्विभाषी अनुवाद',
        scriptHo: 'Translation', scriptSanthali: 'Translation', scriptMundari: 'अनुवाद',
        category: 'Translation', emoji: '🌐', audioClipKey: 'audio_mun_trans',
        quizOptions: { questionText: "मुंडारी से हिंदी अनुवाद करते समय किसका विशेष ध्यान रखना चाहिए?", options: ['क्रिया के अंत व आदरसूचक प्रत्यय', 'केवल संज्ञा', 'केवल विशेषण', 'कुछ नहीं'], correctIndex: 0 },
      },
      {
        id: 'c5_mun_5', grade: '5', subject: 'language_mundari',
        titleHindi: 'मुंडारी मौखिक प्रस्तुति (Oral Presentation)', titleEnglish: 'Speech',
        nameHo: 'Bhashan', nameSanthali: 'Bhashan', nameMundari: 'मौखिक भाषण',
        scriptHo: 'Speech', scriptSanthali: 'Speech', scriptMundari: 'मौखिक भाषण',
        category: 'Oratory', emoji: '🗣️', audioClipKey: 'audio_mun_speech',
        quizOptions: { questionText: "मुंडा समाज में पारंपरिक पंचायत व्यवस्था को क्या कहते हैं?", options: ['पड़हा पंचायत (Parha Panchayat)', 'विधानसभा', 'संसद', 'नगर निगम'], correctIndex: 0 },
      },
    ],
    math: [
      {
        id: 'c5_math_1', grade: '5', subject: 'math',
        titleHindi: 'प्रतिशत: 500 का 20% = 100', titleEnglish: 'Percentage: 20% of 500',
        nameHo: 'Percentage', nameSanthali: 'Percentage', nameMundari: 'प्रतिशत',
        scriptHo: '500 × 20% = 100', scriptSanthali: '500 × 20% = 100', scriptMundari: '५०० का २०% = १००',
        category: 'Percentages', emoji: '📊', audioClipKey: 'audio_percent',
        quizOptions: { questionText: "५०० का २०% कितना होगा?", options: ['१०० (100)', '५० (50)', '१५० (150)', '२०० (200)'], correctIndex: 0 },
      },
      {
        id: 'c5_math_2', grade: '5', subject: 'math',
        titleHindi: 'दशमलव गुणा: 3.5 × 4 = 14', titleEnglish: 'Decimal Multiplication',
        nameHo: 'Decimal Guna', nameSanthali: 'Decimal Guna', nameMundari: 'दशमलव गुणा',
        scriptHo: '3.5 × 4 = 14', scriptSanthali: '3.5 × 4 = 14', scriptMundari: '३.५ × ४ = १४',
        category: 'Decimals', emoji: '✖️', audioClipKey: 'audio_dec_mul',
        quizOptions: { questionText: "३.५ × ४ का सही गुणनफल क्या होगा?", options: ['१४ (14)', '१२ (12)', '१५.५ (15.5)', '१३.५ (13.5)'], correctIndex: 0 },
      },
      {
        id: 'c5_math_3', grade: '5', subject: 'math',
        titleHindi: 'वर्ग क्षेत्रफल = 8 × 8 = 64 वर्ग मी', titleEnglish: 'Area of Square',
        nameHo: 'Square Area', nameSanthali: 'Square Area', nameMundari: 'वर्ग क्षेत्रफल',
        scriptHo: '8 × 8 = 64 sq m', scriptSanthali: '8 × 8 = 64 sq m', scriptMundari: '६४ वर्ग मी',
        category: 'Mensuration', emoji: '🔲', audioClipKey: 'audio_area',
        quizOptions: { questionText: "८ मीटर भुजा वाले वर्गाकार मैदान का क्षेत्रफल क्या होगा?", options: ['६४ वर्ग मीटर (64 sq m)', '३२ वर्ग मीटर', '१६ वर्ग मीटर', '४८ वर्ग मीटर'], correctIndex: 0 },
      },
      {
        id: 'c5_math_4', grade: '5', subject: 'math',
        titleHindi: 'त्रिभुज तीनों कोण योग = 180°', titleEnglish: 'Triangle Angles',
        nameHo: '180° Angles', nameSanthali: '180° Angles', nameMundari: '१८०° कोण योग',
        scriptHo: '180°', scriptSanthali: '180°', scriptMundari: '१८०°',
        category: 'Geometry', emoji: '📐', audioClipKey: 'audio_tri_angles',
        quizOptions: { questionText: "किसी त्रिभुज के तीनों आंतरिक कोणों का कुल योग कितना होता है?", options: ['१८०° (180 Degrees)', '९०° (90 Degrees)', '३६०° (360 Degrees)', '२७०° (270 Degrees)'], correctIndex: 0 },
      },
      {
        id: 'c5_math_5', grade: '5', subject: 'math',
        titleHindi: 'दंड आलेख (Bar Graph Analysis)', titleEnglish: 'Bar Graph',
        nameHo: 'Bar Graph', nameSanthali: 'Bar Graph', nameMundari: 'दंड आलेख',
        scriptHo: 'Bar Graph', scriptSanthali: 'Bar Graph', scriptMundari: 'दंड आलेख',
        category: 'Statistics', emoji: '📈', audioClipKey: 'audio_bar_graph',
        quizOptions: { questionText: "विद्यालय में मासिक छात्र उपस्थिति दर्शाने के लिए कौन सा आलेख सबसे उपयुक्त है?", options: ['स्तंभ आलेख (Bar Graph)', 'वृत्त', 'बिंदु रेखा', 'समीकरण'], correctIndex: 0 },
      },
    ],
    english: [
      {
        id: 'c5_eng_1', grade: '5', subject: 'english',
        titleHindi: 'Active & Passive Voice', titleEnglish: 'Active & Passive Voice',
        nameHo: 'Voice', nameSanthali: 'Voice', nameMundari: 'वाच्य',
        scriptHo: 'Active/Passive', scriptSanthali: 'Active/Passive', scriptMundari: 'वाच्य',
        category: 'Advanced Grammar', emoji: '🔄', audioClipKey: 'audio_voice',
        quizOptions: { questionText: "Passive of: 'Ravi wrote a letter' is:", options: ['A letter was written by Ravi', 'A letter is written by Ravi', 'Ravi is writing a letter', 'A letter wrote Ravi'], correctIndex: 0 },
      },
      {
        id: 'c5_eng_2', grade: '5', subject: 'english',
        titleHindi: 'Prepositions: in, on, at, under', titleEnglish: 'Prepositions',
        nameHo: 'Preposition', nameSanthali: 'Preposition', nameMundari: 'पूर्वसर्ग',
        scriptHo: 'in / on / at', scriptSanthali: 'in / on / at', scriptMundari: 'में / पर',
        category: 'Grammar', emoji: '📍', audioClipKey: 'audio_prep',
        quizOptions: { questionText: "Complete: 'The apple is _____ the table.'", options: ['on', 'in', 'at', 'into'], correctIndex: 0 },
      },
      {
        id: 'c5_eng_3', grade: '5', subject: 'english',
        titleHindi: 'Adverbs: quickly, slowly, neatly', titleEnglish: 'Adverbs',
        nameHo: 'Adverb', nameSanthali: 'Adverb', nameMundari: 'क्रिया विशेषण',
        scriptHo: 'quickly / neatly', scriptSanthali: 'quickly', scriptMundari: 'जल्दी / धीरे',
        category: 'Grammar', emoji: '⚡', audioClipKey: 'audio_adverbs',
        quizOptions: { questionText: "Which word is an Adverb in: 'He ran quickly'?", options: ['quickly', 'ran', 'He', 'none'], correctIndex: 0 },
      },
      {
        id: 'c5_eng_4', grade: '5', subject: 'english',
        titleHindi: 'Formal Letter Format', titleEnglish: 'Letter Writing',
        nameHo: 'Letter', nameSanthali: 'Letter', nameMundari: 'पत्र लेखन',
        scriptHo: 'Formal Letter', scriptSanthali: 'Letter', scriptMundari: 'आवेदन पत्र',
        category: 'Writing Skills', emoji: '✉️', audioClipKey: 'audio_letter',
        quizOptions: { questionText: "An application to the School Headmaster is called a:", options: ['Formal Letter (औपचारिक पत्र)', 'Informal Letter', 'Postcard', 'SMS'], correctIndex: 0 },
      },
      {
        id: 'c5_eng_5', grade: '5', subject: 'english',
        titleHindi: 'Essay Writing: "Save Nature"', titleEnglish: 'Essay Writing',
        nameHo: 'Essay', nameSanthali: 'Essay', nameMundari: 'निबंध लेखन',
        scriptHo: 'Save Forests', scriptSanthali: 'Save Forests', scriptMundari: 'प्रकृति रक्षा',
        category: 'Composition', emoji: '✍️', audioClipKey: 'audio_essay',
        quizOptions: { questionText: "A structured multi-paragraph composition with Introduction, Body, and Conclusion is called an:", options: ['Essay (निबंध)', 'Single word', 'Title', 'Punctuation'], correctIndex: 0 },
      },
    ],
    science: [],
    hindi: [],
  },
};

export const getFlashcardsForClassAndSubject = (grade: ClassGrade, subject: SubjectCategory): ClassSubjectFlashcard[] => {
  const gradeData = FLASHCARD_MATRIX[grade];
  if (gradeData && gradeData[subject] && gradeData[subject].length > 0) {
    return gradeData[subject];
  }
  return FLASHCARD_MATRIX['1']['evs'];
};
