import { FlashcardAnimal } from '../types/models';

export const FLASHCARD_ANIMALS: FlashcardAnimal[] = [
  {
    id: 'cow',
    nameEnglish: 'Cow',
    nameHindi: 'गाय (Cow)',
    nameHo: 'Uri (उरी)',
    nameSanthali: 'Gai (ᱜᱟᱹᱭ)',
    nameMundari: 'Uri (उरी)',
    scriptHo: '𑢣𑣜𑣂',
    scriptSanthali: 'ᱜᱟᱹᱭ',
    scriptMundari: 'उरी',
    category: 'पालतू पशु (Domestic Animals)',
    emoji: '🐄',
    audioClipKey: 'audio_cow',
    quizOptions: {
      questionText: "गाय को 'हो (Ho)' भाषा में क्या कहते हैं?",
      options: ['Uri (उरी)', 'Seta (सेता)', 'Kula (कुला)', 'Hati (हाती)'],
      correctIndex: 0,
    },
  },
  {
    id: 'dog',
    nameEnglish: 'Dog',
    nameHindi: 'कुत्ता (Dog)',
    nameHo: 'Seta (सेता)',
    nameSanthali: 'Seta (ᱥᱮᱛᱟ)',
    nameMundari: 'Seta (सेता)',
    scriptHo: '𑢝𑣈𑣕𑣁',
    scriptSanthali: 'ᱥᱮᱛᱟ',
    scriptMundari: 'सेता',
    category: 'पालतू पशु (Domestic Animals)',
    emoji: '🐕',
    audioClipKey: 'audio_dog',
    quizOptions: {
      questionText: "संथाली (Ol Chiki: ᱥᱮᱛᱟ) का हिंदी अर्थ क्या है?",
      options: ['बिल्ली', 'कुत्ता', 'बकरी', 'घोड़ा'],
      correctIndex: 1,
    },
  },
  {
    id: 'cat',
    nameEnglish: 'Cat',
    nameHindi: 'बिल्ली (Cat)',
    nameHo: 'Bili (बिली)',
    nameSanthali: 'Pusi (ᱯᱩᱥᱤ)',
    nameMundari: 'Bili (बिली)',
    scriptHo: '𑢷𑣂𑢚𑣂',
    scriptSanthali: 'ᱯᱩᱥᱤ',
    scriptMundari: 'बिली',
    category: 'पालतू पशु (Domestic Animals)',
    emoji: '🐈',
    audioClipKey: 'audio_cat',
    quizOptions: {
      questionText: "संथाली में 'Pusi (ᱯᱩᱥᱤ)' किसे कहते हैं?",
      options: ['गाय', 'चूहा', 'बिल्ली', 'पक्षी'],
      correctIndex: 2,
    },
  },
  {
    id: 'elephant',
    nameEnglish: 'Elephant',
    nameHindi: 'हाथी (Elephant)',
    nameHo: 'Hati (हाती)',
    nameSanthali: 'Hathi (ᱦᱟᱹᱛᱤ)',
    nameMundari: 'Hati (हाती)',
    scriptHo: '𑢹𑣁𑣕𑣂',
    scriptSanthali: 'ᱦᱟᱹᱛᱤ',
    scriptMundari: 'हाती',
    category: 'जंगली जानवर (Wild Animals)',
    emoji: '🐘',
    audioClipKey: 'audio_elephant',
    quizOptions: {
      questionText: "'हाथी' को मुंडारी व हो भाषा में क्या उच्चारित किया जाता है?",
      options: ['Buru', 'Hati', 'Daru', 'Bir'],
      correctIndex: 1,
    },
  },
  {
    id: 'tiger',
    nameEnglish: 'Tiger',
    nameHindi: 'बाघ (Tiger)',
    nameHo: 'Kula (कुला)',
    nameSanthali: 'Tarup (ᱛᱟᱹᱨᱩᱵ)',
    nameMundari: 'Kula (कुला)',
    scriptHo: '𑢢𑣉𑢚𑣁',
    scriptSanthali: 'ᱛᱟᱹᱨᱩᱵ',
    scriptMundari: 'कुला',
    category: 'जंगली जानवर (Wild Animals)',
    emoji: '🐅',
    audioClipKey: 'audio_tiger',
    quizOptions: {
      questionText: "संथाली में 'Tarup (ᱛᱟᱹᱨᱩᱵ)' का सही अर्थ क्या है?",
      options: ['शेर', 'बाघ', 'भालू', 'हिरण'],
      correctIndex: 1,
    },
  },
  {
    id: 'bird',
    nameEnglish: 'Bird',
    nameHindi: 'चिड़िया (Bird)',
    nameHo: 'Chene (चेने)',
    nameSanthali: 'Chene (ᱪᱮᱬᱮ)',
    nameMundari: 'Chene (चेने)',
    scriptHo: '𑢮𑣈𑣓𑣈',
    scriptSanthali: 'ᱪᱮᱬᱮ',
    scriptMundari: 'चेने',
    category: 'पक्षी (Birds)',
    emoji: '🐦',
    audioClipKey: 'audio_bird',
    quizOptions: {
      questionText: "हो, संथाली व मुंडारी तीनों में 'Chene' किसका नाम है?",
      options: ['मछली', 'चिड़िया', 'पेड़', 'फूल'],
      correctIndex: 1,
    },
  },
  {
    id: 'fish',
    nameEnglish: 'Fish',
    nameHindi: 'मछली (Fish)',
    nameHo: 'Haku (हाकु)',
    nameSanthali: 'Haku (ᱦᱟᱹᱠᱩ)',
    nameMundari: 'Hai (हाई)',
    scriptHo: '𑢹𑣁𑢢𑣉',
    scriptSanthali: 'ᱦᱟᱹᱠᱩ',
    scriptMundari: 'हाई',
    category: 'जलचर (Water Creatures)',
    emoji: '🐟',
    audioClipKey: 'audio_fish',
    quizOptions: {
      questionText: "मुंडारी में मछली को 'हाई (Hai)' और हो/संथाली में क्या कहते हैं?",
      options: ['Da', 'Haku', 'Gada', 'Singi'],
      correctIndex: 1,
    },
  },
];
